In [1]:
import os
import pandas as pd
import numpy as np
from google.cloud import bigquery

os.environ["GOOGLE_APPLICATION_CREDENTIALS"]="../esoteric-bruin-379522-1ac227ab6db1.json" # lokalizacja pobranego klucza z punktu 1.4.
client = bigquery.Client()

pd.set_option('display.max_columns', None)

#### USTAW PATH_PREFIX
PATH_REFIX = '../zad1/'

## Ćwiczenie 1

Połącz ze sobą wszystkie dane otrzymane w części 4 z zadania 1. Nowy zbiór danych zapisz jako oddzielny obiekt DataFrame. Jeżeli uważasz, że należy stworzyć kilka takich obiektów, zrób to i zapisz swoje uzasadnienie. Pamiętaj o ciągłej konieczności zachowania czystości danych. Wynik tego zadania zapisz w pliku / plikach CSV.

In [2]:
df41 = pd.read_csv(f"{PATH_REFIX}kraje.csv")
df41

,country_name,location_key,iso_3166_1_alpha_3,population,population_male,population_female,population_density,gdp_usd,area_sq_km
0,Estonia,EE,EST,1324820,625635,699185,30.400,30722303000,45340
1,Romania,RO,ROU,19414458,9500450,9914008,83.100,241475766400,238400
2,United States of America,US,USA,331002647,163786016,167216631,36.185,21374418877706,9831510
3,Azerbaijan,AZ,AZE,10139175,5064664,5074511,122.664,48047647058,86600
4,Bangladesh,BD,BGD,164689383,83259108,81430275,1265.187,302571254131,147630
...,...,...,...,...,...,...,...,...,...
197,Portugal,PT,PRT,10276617,4852366,5424251,113.000,240597516000,92225
198,Trinidad and Tobago,TT,TTO,1399491,690947,708544,272.805,24100202833,5130
199,Saint Vincent and the Grenadines,VC,VCT,110947,56218,54729,284.479,825385185,390
200,Samoa,WS,WSM,198410,102703,95707,70.110,850655017,2840
201,Zambia,ZM,ZMB,18383956,9103006,9280950,24.730,23064722446,752610

In [3]:
# 4.2 statyski zachorowań dla całego świata

q1 = ("""
select location_key,
    date,
    new_confirmed, 
    new_deceased,
    new_recovered,
    new_intensive_care_patients
from `bigquery-public-data.covid19_open_data.covid19_open_data`
where aggregation_level=0 
and date between '2020-07-01' and '2020-12-31'
""")
query_job = client.query(q1)
query_result = query_job.result()
df42 = query_result.to_dataframe()
df42 = df42.drop_duplicates().fillna(0)

df42

,location_key,date,new_confirmed,new_deceased,new_recovered,new_intensive_care_patients
0,AR,2020-12-23,9374,127,0,76
1,AR,2020-12-08,2927,164,0,80
2,BR,2020-12-25,22967,482,1082,2
3,CO,2020-07-15,7107,258,2963,0
4,CO,2020-11-04,9282,252,8329,0
...,...,...,...,...,...,...
45259,US,2020-07-04,49269,522,0,40
45260,US,2020-10-22,74272,922,0,163
45261,US,2020-08-04,51750,1085,0,167
45262,US,2020-10-08,55019,732,0,105
45263,US,2020-10-26,69434,705,0,122

In [4]:
df43 = pd.read_csv(f"{PATH_REFIX}4.3.csv")
df43

,location_key,date,new_deceased,new_deceased_age_0,new_deceased_age_1,new_deceased_age_2,new_deceased_age_3,new_deceased_age_4,new_deceased_age_5,new_deceased_age_6,new_deceased_age_7,new_deceased_age_8,new_deceased_age_9,new_confirmed,new_confirmed_age_0,new_confirmed_age_1,new_confirmed_age_2,new_confirmed_age_3,new_confirmed_age_4,new_confirmed_age_5,new_confirmed_age_6,new_confirmed_age_7,new_confirmed_age_8,new_confirmed_age_9
0,AR,2020-08-31,303,0,1,1,3,13,24,59,83,87,32,10056,244,414,1802,2484,2044,1427,797,453,264,118
1,AR,2020-10-05,372,1,0,1,6,11,49,74,102,83,45,13230,290,551,2337,3207,2743,1874,1142,619,344,119
2,AR,2020-09-01,308,0,0,1,4,13,21,53,96,83,37,11517,209,430,2083,2818,2447,1725,905,497,281,116
3,AR,2020-11-18,242,1,2,0,3,10,17,55,62,66,26,9842,221,497,1937,2282,1909,1341,853,490,226,84
4,BR,2020-09-13,415,2,0,8,21,35,82,142,174,129,43,14768,326,313,1306,1665,1342,907,602,293,342,26
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
45259,TH,2020-11-24,0,0,0,0,0,0,0,0,0,0,0,2,1,0,0,1,0,0,0,0,0,0
45260,TW,2020-12-06,0,0,0,0,0,0,0,0,0,0,0,22,0,0,11,6,5,0,0,0,0,0
45261,TW,2020-11-17,0,0,0,0,0,0,0,0,0,0,0,2,0,0,0,1,0,1,0,0,0,0
45262,US,2020-07-05,445,0,0,0,0,0,0,0,0,0,0,39919,542,1623,4349,3223,2585,2271,1295,644,0,0
45263,US,2020-10-25,606,0,0,0,0,0,0,0,0,0,0,65177,1472,4226,6784,5868,5433,5129,3755,2135,0,0

In [5]:
df44 = pd.read_csv(f"{PATH_REFIX}4.4.csv")
df44

,location_key,date,new_persons_vaccinated,new_persons_fully_vaccinated,cumulative_persons_fully_vaccinated,adult_male_mortality_rate,adult_female_mortality_rate
0,CH,2020-12-30,1659,2,10,58.204,35.896
1,US,2020-12-18,409914,1262,10854,139.141,81.935
2,CZ,2020-12-31,1313,0,1,108.785,51.325
3,CH,2020-12-21,1,1,1,58.204,35.896
4,CA,2020-12-29,13012,1,2,82.625,51.763
...,...,...,...,...,...,...,...
83,FR,2020-12-30,443,18,134,95.352,48.187
84,IL,2020-12-20,7393,0,4,70.873,39.638
85,CA,2020-12-28,6626,0,1,82.625,51.763
86,BE,2020-12-28,340,0,0,80.262,49.245
87,IL,2020-12-30,153161,0,6,70.873,39.638

In [6]:
df451 = pd.read_csv(f"{PATH_REFIX}4.5.1.csv")

df451

,location_key,date,cumulative_confirmed,cumulative_persons_fully_vaccinated,population,hdi
0,CA,2020-12-29,266,2,37742157,0.926
1,AR,2020-12-29,1638156,3,44938712,0.825
2,BR,2020-07-29,2552265,0,212559409,0.754
3,BR,2020-09-25,4689613,0,212559409,0.754
4,BR,2020-09-29,4777522,0,212559409,0.754
...,...,...,...,...,...,...
472,AU,2020-11-28,27885,0,25499881,0.939
473,AU,2020-08-02,17923,0,25499881,0.939
474,BR,2020-08-17,3359570,0,212559409,0.754
475,BR,2020-10-09,5055888,0,212559409,0.754
476,BR,2020-10-07,5000694,0,212559409,0.754

In [7]:
df452 = pd.read_csv(f"{PATH_REFIX}4.5.2.csv")
df452

,date,location_key,new_confirmed,mobility_retail_and_recreation,mobility_grocery_and_pharmacy,mobility_parks,mobility_transit_stations,mobility_workplaces,mobility_residential
0,2020-12-08,AT,2631,-50,-48,-8,-60,-79,24
1,2020-08-30,BG,76,8,-4,132,4,3,-11
2,2020-08-23,BG,99,8,-4,144,5,3,-11
3,2020-08-08,BO,1164,-70,-59,-69,-76,-54,30
4,2020-08-12,BW,148,-33,-16,2,-47,-37,28
...,...,...,...,...,...,...,...,...,...
22419,2020-11-20,PA,1200,-40,-19,-54,-37,-29,19
22420,2020-08-15,ZW,85,-15,3,5,-23,3,19
22421,2020-12-03,AE,1311,-14,5,5,-42,-59,19
22422,2020-07-26,CR,629,-67,-39,-63,-67,-33,19
22423,2020-07-30,ZA,11003,-23,-5,-18,-49,-38,19

In [8]:
df453 = pd.read_csv(f"{PATH_REFIX}4.5.3.csv")
df453

,date,location_key,new_tested,new_confirmed,new_deceased,search_trends_cough,search_trends_fever
0,2020-12-05,GB,354378,12893,396,4.24,3.35
1,2020-07-30,GB,206656,946,10,3.37,4.52
2,2020-10-24,IE,15772,1020,7,4.39,4.44
3,2020-08-29,IE,5659,41,0,4.87,5.33
4,2020-11-10,IE,10790,358,5,3.77,3.92
...,...,...,...,...,...,...,...
888,2020-08-31,NZ,8939,14,0,7.68,5.14
889,2020-12-07,NZ,2315,6,0,10.44,6.17
890,2020-08-26,NZ,8786,7,0,7.37,4.84
891,2020-07-05,US,725934,39919,445,3.29,4.24
892,2020-10-25,US,955237,65177,606,3.70,3.30

## Łączenie

In [9]:
# laczenie dat wyszukiwań
df = pd.merge(df41, df453, how="right", on="location_key")
df

,country_name,location_key,iso_3166_1_alpha_3,population,population_male,population_female,population_density,gdp_usd,area_sq_km,date,new_tested,new_confirmed,new_deceased,search_trends_cough,search_trends_fever
0,United Kingdom,GB,GBR,66647112,32901036,33746076,273.800,2860009176200,243610,2020-12-05,354378,12893,396,4.24,3.35
1,United Kingdom,GB,GBR,66647112,32901036,33746076,273.800,2860009176200,243610,2020-07-30,206656,946,10,3.37,4.52
2,Ireland,IE,IRL,4904240,2428881,2475359,70.900,382365076000,70280,2020-10-24,15772,1020,7,4.39,4.44
3,Ireland,IE,IRL,4904240,2428881,2475359,70.900,382365076000,70280,2020-08-29,5659,41,0,4.87,5.33
4,Ireland,IE,IRL,4904240,2428881,2475359,70.900,382365076000,70280,2020-11-10,10790,358,5,3.77,3.92
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
888,New Zealand,NZ,NZL,4822233,2370163,2452070,18.314,206928765543,267710,2020-08-31,8939,14,0,7.68,5.14
889,New Zealand,NZ,NZL,4822233,2370163,2452070,18.314,206928765543,267710,2020-12-07,2315,6,0,10.44,6.17
890,New Zealand,NZ,NZL,4822233,2370163,2452070,18.314,206928765543,267710,2020-08-26,8786,7,0,7.37,4.84
891,United States of America,US,USA,331002647,163786016,167216631,36.185,21374418877706,9831510,2020-07-05,725934,39919,445,3.29,4.24
892,United States of America,US,USA,331002647,163786016,167216631,36.185,21374418877706,9831510,2020-10-25,955237,65177,606,3.70,3.30

In [17]:
# laczenie df452 - mobility
df2 = pd.merge(df, df452, how="left", on=["location_key", "date", "new_confirmed"])
df2

,country_name,location_key,iso_3166_1_alpha_3,population,population_male,population_female,population_density,gdp_usd,area_sq_km,date,new_tested,new_confirmed,new_deceased,search_trends_cough,search_trends_fever,mobility_retail_and_recreation,mobility_grocery_and_pharmacy,mobility_parks,mobility_transit_stations,mobility_workplaces,mobility_residential
0,United Kingdom,GB,GBR,66647112,32901036,33746076,273.800,2860009176200,243610,2020-12-05,354378,12893,396,4.24,3.35,-36.0,-6.0,-8.0,-41.0,-13.0,8.0
1,United Kingdom,GB,GBR,66647112,32901036,33746076,273.800,2860009176200,243610,2020-07-30,206656,946,10,3.37,4.52,-23.0,-7.0,120.0,-41.0,-48.0,13.0
2,Ireland,IE,IRL,4904240,2428881,2475359,70.900,382365076000,70280,2020-10-24,15772,1020,7,4.39,4.44,NaN,NaN,NaN,NaN,NaN,NaN
3,Ireland,IE,IRL,4904240,2428881,2475359,70.900,382365076000,70280,2020-08-29,5659,41,0,4.87,5.33,NaN,NaN,NaN,NaN,NaN,NaN
4,Ireland,IE,IRL,4904240,2428881,2475359,70.900,382365076000,70280,2020-11-10,10790,358,5,3.77,3.92,NaN,NaN,NaN,NaN,NaN,NaN
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
888,New Zealand,NZ,NZL,4822233,2370163,2452070,18.314,206928765543,267710,2020-08-31,8939,14,0,7.68,5.14,-11.0,-9.0,-19.0,-35.0,7.0,4.0
889,New Zealand,NZ,NZL,4822233,2370163,2452070,18.314,206928765543,267710,2020-12-07,2315,6,0,10.44,6.17,3.0,-2.0,-11.0,-25.0,13.0,1.0
890,New Zealand,NZ,NZL,4822233,2370163,2452070,18.314,206928765543,267710,2020-08-26,8786,7,0,7.37,4.84,-25.0,-11.0,-23.0,-51.0,-16.0,11.0
891,United States of America,US,USA,331002647,163786016,167216631,36.185,21374418877706,9831510,2020-07-05,725934,39919,445,3.29,4.24,-22.0,-10.0,53.0,-23.0,-19.0,3.0
892,United States of America,US,USA,331002647,163786016,167216631,36.185,21374418877706,9831510,2020-10-25,955237,65177,606,3.70,3.30,-18.0,-8.0,1.0,-27.0,-15.0,4.0

In [18]:
df3 = pd.merge(df2, df451, how="left", on=["location_key", "population", 'date'])
df3

,country_name,location_key,iso_3166_1_alpha_3,population,population_male,population_female,population_density,gdp_usd,area_sq_km,date,new_tested,new_confirmed,new_deceased,search_trends_cough,search_trends_fever,mobility_retail_and_recreation,mobility_grocery_and_pharmacy,mobility_parks,mobility_transit_stations,mobility_workplaces,mobility_residential,cumulative_confirmed,cumulative_persons_fully_vaccinated,hdi
0,United Kingdom,GB,GBR,66647112,32901036,33746076,273.800,2860009176200,243610,2020-12-05,354378,12893,396,4.24,3.35,-36.0,-6.0,-8.0,-41.0,-13.0,8.0,NaN,NaN,NaN
1,United Kingdom,GB,GBR,66647112,32901036,33746076,273.800,2860009176200,243610,2020-07-30,206656,946,10,3.37,4.52,-23.0,-7.0,120.0,-41.0,-48.0,13.0,NaN,NaN,NaN
2,Ireland,IE,IRL,4904240,2428881,2475359,70.900,382365076000,70280,2020-10-24,15772,1020,7,4.39,4.44,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
3,Ireland,IE,IRL,4904240,2428881,2475359,70.900,382365076000,70280,2020-08-29,5659,41,0,4.87,5.33,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
4,Ireland,IE,IRL,4904240,2428881,2475359,70.900,382365076000,70280,2020-11-10,10790,358,5,3.77,3.92,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
888,New Zealand,NZ,NZL,4822233,2370163,2452070,18.314,206928765543,267710,2020-08-31,8939,14,0,7.68,5.14,-11.0,-9.0,-19.0,-35.0,7.0,4.0,NaN,NaN,NaN
889,New Zealand,NZ,NZL,4822233,2370163,2452070,18.314,206928765543,267710,2020-12-07,2315,6,0,10.44,6.17,3.0,-2.0,-11.0,-25.0,13.0,1.0,NaN,NaN,NaN
890,New Zealand,NZ,NZL,4822233,2370163,2452070,18.314,206928765543,267710,2020-08-26,8786,7,0,7.37,4.84,-25.0,-11.0,-23.0,-51.0,-16.0,11.0,NaN,NaN,NaN
891,United States of America,US,USA,331002647,163786016,167216631,36.185,21374418877706,9831510,2020-07-05,725934,39919,445,3.29,4.24,-22.0,-10.0,53.0,-23.0,-19.0,3.0,NaN,NaN,NaN
892,United States of America,US,USA,331002647,163786016,167216631,36.185,21374418877706,9831510,2020-10-25,955237,65177,606,3.70,3.30,-18.0,-8.0,1.0,-27.0,-15.0,4.0,NaN,NaN,NaN

In [19]:
df4 = pd.merge(df3, df44, how='left', on=['location_key', 'date', 'cumulative_persons_fully_vaccinated', 'cumulative_persons_fully_vaccinated'])

df4 = df4.set_index(['location_key'])


# df4.update(tt)
df4

,country_name,iso_3166_1_alpha_3,population,population_male,population_female,population_density,gdp_usd,area_sq_km,date,new_tested,new_confirmed,new_deceased,search_trends_cough,search_trends_fever,mobility_retail_and_recreation,mobility_grocery_and_pharmacy,mobility_parks,mobility_transit_stations,mobility_workplaces,mobility_residential,cumulative_confirmed,cumulative_persons_fully_vaccinated,hdi,new_persons_vaccinated,new_persons_fully_vaccinated,adult_male_mortality_rate,adult_female_mortality_rate
location_key,,,,,,,,,,,,,,,,,,,,,,,,,,,
GB,United Kingdom,GBR,66647112,32901036,33746076,273.800,2860009176200,243610,2020-12-05,354378,12893,396,4.24,3.35,-36.0,-6.0,-8.0,-41.0,-13.0,8.0,NaN,NaN,NaN,NaN,NaN,NaN,NaN
GB,United Kingdom,GBR,66647112,32901036,33746076,273.800,2860009176200,243610,2020-07-30,206656,946,10,3.37,4.52,-23.0,-7.0,120.0,-41.0,-48.0,13.0,NaN,NaN,NaN,NaN,NaN,NaN,NaN
IE,Ireland,IRL,4904240,2428881,2475359,70.900,382365076000,70280,2020-10-24,15772,1020,7,4.39,4.44,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
IE,Ireland,IRL,4904240,2428881,2475359,70.900,382365076000,70280,2020-08-29,5659,41,0,4.87,5.33,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
IE,Ireland,IRL,4904240,2428881,2475359,70.900,382365076000,70280,2020-11-10,10790,358,5,3.77,3.92,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
NZ,New Zealand,NZL,4822233,2370163,2452070,18.314,206928765543,267710,2020-08-31,8939,14,0,7.68,5.14,-11.0,-9.0,-19.0,-35.0,7.0,4.0,NaN,NaN,NaN,NaN,NaN,NaN,NaN
NZ,New Zealand,NZL,4822233,2370163,2452070,18.314,206928765543,267710,2020-12-07,2315,6,0,10.44,6.17,3.0,-2.0,-11.0,-25.0,13.0,1.0,NaN,NaN,NaN,NaN,NaN,NaN,NaN
NZ,New Zealand,NZL,4822233,2370163,2452070,18.314,206928765543,267710,2020-08-26,8786,7,0,7.37,4.84,-25.0,-11.0,-23.0,-51.0,-16.0,11.0,NaN,NaN,NaN,NaN,NaN,NaN,NaN
US,United States of America,USA,331002647,163786016,167216631,36.185,21374418877706,9831510,2020-07-05,725934,39919,445,3.29,4.24,-22.0,-10.0,53.0,-23.0,-19.0,3.0,NaN,NaN,NaN,NaN,NaN,NaN,NaN
US,United States of America,USA,331002647,163786016,167216631,36.185,21374418877706,9831510,2020-10-25,955237,65177,606,3.70,3.30,-18.0,-8.0,1.0,-27.0,-15.0,4.0,NaN,NaN,NaN,NaN,NaN,NaN,NaN

In [22]:
#df43 = df43.set_index('location_key')

df5 = pd.merge(df4, df43, on=['location_key', 'date', 'new_deceased', 'new_confirmed'], how='inner')
df5.drop_duplicates()

,location_key,country_name,iso_3166_1_alpha_3,population,population_male,population_female,population_density,gdp_usd,area_sq_km,date,new_tested,new_confirmed,new_deceased,search_trends_cough,search_trends_fever,mobility_retail_and_recreation,mobility_grocery_and_pharmacy,mobility_parks,mobility_transit_stations,mobility_workplaces,mobility_residential,cumulative_confirmed,cumulative_persons_fully_vaccinated,hdi,new_persons_vaccinated,new_persons_fully_vaccinated,adult_male_mortality_rate,adult_female_mortality_rate,new_deceased_age_0,new_deceased_age_1,new_deceased_age_2,new_deceased_age_3,new_deceased_age_4,new_deceased_age_5,new_deceased_age_6,new_deceased_age_7,new_deceased_age_8,new_deceased_age_9,new_confirmed_age_0,new_confirmed_age_1,new_confirmed_age_2,new_confirmed_age_3,new_confirmed_age_4,new_confirmed_age_5,new_confirmed_age_6,new_confirmed_age_7,new_confirmed_age_8,new_confirmed_age_9
0,GB,United Kingdom,GBR,66647112,32901036,33746076,273.800,2860009176200,243610,2020-12-05,354378,12893,396,4.24,3.35,-36.0,-6.0,-8.0,-41.0,-13.0,8.0,NaN,NaN,NaN,NaN,NaN,NaN,NaN,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0
1,GB,United Kingdom,GBR,66647112,32901036,33746076,273.800,2860009176200,243610,2020-07-30,206656,946,10,3.37,4.52,-23.0,-7.0,120.0,-41.0,-48.0,13.0,NaN,NaN,NaN,NaN,NaN,NaN,NaN,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0
2,IE,Ireland,IRL,4904240,2428881,2475359,70.900,382365076000,70280,2020-10-24,15772,1020,7,4.39,4.44,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0
3,IE,Ireland,IRL,4904240,2428881,2475359,70.900,382365076000,70280,2020-08-29,5659,41,0,4.87,5.33,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0
4,IE,Ireland,IRL,4904240,2428881,2475359,70.900,382365076000,70280,2020-11-10,10790,358,5,3.77,3.92,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
888,NZ,New Zealand,NZL,4822233,2370163,2452070,18.314,206928765543,267710,2020-08-31,8939,14,0,7.68,5.14,-11.0,-9.0,-19.0,-35.0,7.0,4.0,NaN,NaN,NaN,NaN,NaN,NaN,NaN,0,0,0,0,0,0,0,0,0,0,1,1,6,3,1,2,0,0,0,0
889,NZ,New Zealand,NZL,4822233,2370163,2452070,18.314,206928765543,267710,2020-12-07,2315,6,0,10.44,6.17,3.0,-2.0,-11.0,-25.0,13.0,1.0,NaN,NaN,NaN,NaN,NaN,NaN,NaN,0,0,0,0,0,0,0,0,0,0,0,0,2,1,2,1,0,0,0,0
890,NZ,New Zealand,NZL,4822233,2370163,2452070,18.314,206928765543,267710,2020-08-26,8786,7,0,7.37,4.84,-25.0,-11.0,-23.0,-51.0,-16.0,11.0,NaN,NaN,NaN,NaN,NaN,NaN,NaN,0,0,0,0,0,0,0,0,0,0,0,2,1,1,2,1,0,0,0,0
891,US,United States of America,USA,331002647,163786016,167216631,36.185,21374418877706,9831510,2020-07-05,725934,39919,445,3.29,4.24,-22.0,-10.0,53.0,-23.0,-19.0,3.0,NaN,NaN,NaN,NaN,NaN,NaN,NaN,0,0,0,0,0,0,0,0,0,0,542,1623,4349,3223,2585,2271,1295,644,0,0
892,US,United States of America,USA,331002647,163786016,167216631,36.185,21374418877706,9831510,2020-10-25,955237,65177,606,3.70,3.30,-18.0,-8.0,1.0,-27.0,-15.0,4.0,NaN,NaN,NaN,NaN,NaN,NaN,NaN,0,0,0,0,0,0,0,0,0,0,1472,4226,6784,5868,5433,5129,3755,2135,0,0

In [23]:
df42['new_deceased'] = df42['new_deceased'].astype(float)
df42['new_confirmed'] = df42['new_confirmed'].astype(float)
fl = pd.merge(df5, df42, on=['location_key', 'date', 'new_confirmed', 'new_deceased'], how='left').drop_duplicates()

fl.to_csv("zad2.1.csv", index=False)
fl

,location_key,country_name,iso_3166_1_alpha_3,population,population_male,population_female,population_density,gdp_usd,area_sq_km,date,new_tested,new_confirmed,new_deceased,search_trends_cough,search_trends_fever,mobility_retail_and_recreation,mobility_grocery_and_pharmacy,mobility_parks,mobility_transit_stations,mobility_workplaces,mobility_residential,cumulative_confirmed,cumulative_persons_fully_vaccinated,hdi,new_persons_vaccinated,new_persons_fully_vaccinated,adult_male_mortality_rate,adult_female_mortality_rate,new_deceased_age_0,new_deceased_age_1,new_deceased_age_2,new_deceased_age_3,new_deceased_age_4,new_deceased_age_5,new_deceased_age_6,new_deceased_age_7,new_deceased_age_8,new_deceased_age_9,new_confirmed_age_0,new_confirmed_age_1,new_confirmed_age_2,new_confirmed_age_3,new_confirmed_age_4,new_confirmed_age_5,new_confirmed_age_6,new_confirmed_age_7,new_confirmed_age_8,new_confirmed_age_9,new_recovered,new_intensive_care_patients
0,GB,United Kingdom,GBR,66647112,32901036,33746076,273.800,2860009176200,243610,2020-12-05,354378,12893,396,4.24,3.35,-36.0,-6.0,-8.0,-41.0,-13.0,8.0,NaN,NaN,NaN,NaN,NaN,NaN,NaN,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,<NA>,<NA>
1,GB,United Kingdom,GBR,66647112,32901036,33746076,273.800,2860009176200,243610,2020-07-30,206656,946,10,3.37,4.52,-23.0,-7.0,120.0,-41.0,-48.0,13.0,NaN,NaN,NaN,NaN,NaN,NaN,NaN,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,<NA>,<NA>
2,IE,Ireland,IRL,4904240,2428881,2475359,70.900,382365076000,70280,2020-10-24,15772,1020,7,4.39,4.44,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,<NA>,<NA>
3,IE,Ireland,IRL,4904240,2428881,2475359,70.900,382365076000,70280,2020-08-29,5659,41,0,4.87,5.33,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,<NA>,<NA>
4,IE,Ireland,IRL,4904240,2428881,2475359,70.900,382365076000,70280,2020-11-10,10790,358,5,3.77,3.92,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,<NA>,<NA>
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
888,NZ,New Zealand,NZL,4822233,2370163,2452070,18.314,206928765543,267710,2020-08-31,8939,14,0,7.68,5.14,-11.0,-9.0,-19.0,-35.0,7.0,4.0,NaN,NaN,NaN,NaN,NaN,NaN,NaN,0,0,0,0,0,0,0,0,0,0,1,1,6,3,1,2,0,0,0,0,<NA>,<NA>
889,NZ,New Zealand,NZL,4822233,2370163,2452070,18.314,206928765543,267710,2020-12-07,2315,6,0,10.44,6.17,3.0,-2.0,-11.0,-25.0,13.0,1.0,NaN,NaN,NaN,NaN,NaN,NaN,NaN,0,0,0,0,0,0,0,0,0,0,0,0,2,1,2,1,0,0,0,0,<NA>,<NA>
890,NZ,New Zealand,NZL,4822233,2370163,2452070,18.314,206928765543,267710,2020-08-26,8786,7,0,7.37,4.84,-25.0,-11.0,-23.0,-51.0,-16.0,11.0,NaN,NaN,NaN,NaN,NaN,NaN,NaN,0,0,0,0,0,0,0,0,0,0,0,2,1,1,2,1,0,0,0,0,<NA>,<NA>
891,US,United States of America,USA,331002647,163786016,167216631,36.185,21374418877706,9831510,2020-07-05,725934,39919,445,3.29,4.24,-22.0,-10.0,53.0,-23.0,-19.0,3.0,NaN,NaN,NaN,NaN,NaN,NaN,NaN,0,0,0,0,0,0,0,0,0,0,542,1623,4349,3223,2585,2271,1295,644,0,0,<NA>,<NA>
892,US,United States of America,USA,331002647,163786016,167216631,36.185,21374418877706,9831510,2020-10-25,955237,65177,606,3.70,3.30,-18.0,-8.0,1.0,-27.0,-15.0,4.0,NaN,NaN,NaN,NaN,NaN,NaN,NaN,0,0,0,0,0,0,0,0,0,0,1472,4226,6784,5868,5433,5129,3755,2135,0,0,<NA>,<NA>

# Ćzęść 2

In [39]:
# 1 PKB
gdp = pd.read_csv('gdp.csv')
gdp.head(20)

   Country Name Country Code  Year         Value
0    Arab World          ARB  1968  2.576068e+10
1    Arab World          ARB  1969  2.843420e+10
2    Arab World          ARB  1970  3.138550e+10
3    Arab World          ARB  1971  3.642691e+10
4    Arab World          ARB  1972  4.331606e+10
5    Arab World          ARB  1973  5.501839e+10
6    Arab World          ARB  1974  1.051458e+11
7    Arab World          ARB  1975  1.163370e+11
8    Arab World          ARB  1976  1.448462e+11
9    Arab World          ARB  1977  1.673083e+11
10   Arab World          ARB  1978  1.835555e+11
11   Arab World          ARB  1979  2.486462e+11
12   Arab World          ARB  1980  3.381775e+11
13   Arab World          ARB  1981  3.485928e+11
14   Arab World          ARB  1982  3.243288e+11
15   Arab World          ARB  1983  3.039625e+11
16   Arab World          ARB  1984  3.079408e+11
17   Arab World          ARB  1985  3.038936e+11
18   Arab World          ARB  1986  2.890292e+11
19   Arab World          ARB  1987  3.126817e+11

In [40]:
# 2 PKB

gdp['Year'] = 'GDP ' + gdp['Year'].astype(str)
rimland = gdp.pivot(index=['Country Code', 'Country Name'], columns=['Year'], values='Value')
rimland

,Year,GDP 1960,GDP 1961,GDP 1962,GDP 1963,GDP 1964,GDP 1965,GDP 1966,GDP 1967,GDP 1968,GDP 1969,GDP 1970,GDP 1971,GDP 1972,GDP 1973,GDP 1974,GDP 1975,GDP 1976,GDP 1977,GDP 1978,GDP 1979,GDP 1980,GDP 1981,GDP 1982,GDP 1983,GDP 1984,GDP 1985,GDP 1986,GDP 1987,GDP 1988,GDP 1989,GDP 1990,GDP 1991,GDP 1992,GDP 1993,GDP 1994,GDP 1995,GDP 1996,GDP 1997,GDP 1998,GDP 1999,GDP 2000,GDP 2001,GDP 2002,GDP 2003,GDP 2004,GDP 2005,GDP 2006,GDP 2007,GDP 2008,GDP 2009,GDP 2010,GDP 2011,GDP 2012,GDP 2013,GDP 2014,GDP 2015,GDP 2016
Country Code,Country Name,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,
ABW,Aruba,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,1.330168e+09,1.320670e+09,1.379888e+09,1.531844e+09,1.665363e+09,1.722799e+09,1.873453e+09,1.920263e+09,1.941095e+09,2.021302e+09,2.228279e+09,2.331006e+09,2.421475e+09,2.623726e+09,2.791961e+09,2.498933e+09,2.467704e+09,2.584464e+09,NaN,NaN,NaN,NaN,NaN
AFG,Afghanistan,5.377778e+08,5.488889e+08,5.466667e+08,7.511112e+08,8.000000e+08,1.006667e+09,1.400000e+09,1.673333e+09,1.373333e+09,1.408889e+09,1.748887e+09,1.831109e+09,1.595555e+09,1.733333e+09,2.155555e+09,2.366667e+09,2.555556e+09,2.953333e+09,3.300000e+09,3.697940e+09,3.641723e+09,3.478788e+09,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,2.461666e+09,4.128821e+09,4.583644e+09,5.285466e+09,6.275074e+09,7.057598e+09,9.843842e+09,1.019053e+10,1.248694e+10,1.593680e+10,1.793024e+10,2.053654e+10,2.004633e+10,2.005019e+10,1.921556e+10,1.946902e+10
AGO,Angola,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,6.684492e+09,6.684492e+09,6.684492e+09,6.684492e+09,1.002674e+10,1.002674e+10,1.211861e+10,5.684292e+09,5.278183e+09,4.059352e+09,5.039552e+09,7.526447e+09,7.648377e+09,6.445042e+09,6.152923e+09,9.129595e+09,8.936064e+09,1.249735e+10,1.418895e+10,1.964085e+10,2.823371e+10,4.178948e+10,6.044892e+10,8.417803e+10,7.549238e+10,8.247091e+10,1.041159e+11,1.153984e+11,1.249121e+11,1.267769e+11,1.029622e+11,9.533511e+10
ALB,Albania,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,1.924242e+09,1.965385e+09,2.173750e+09,2.156625e+09,2.126000e+09,2.335125e+09,2.101625e+09,1.139167e+09,7.094526e+08,1.228071e+09,1.985674e+09,2.424499e+09,3.314898e+09,2.359903e+09,2.707124e+09,3.414761e+09,3.632044e+09,4.060759e+09,4.435079e+09,5.746946e+09,7.314865e+09,8.158549e+09,8.992642e+09,1.070101e+10,1.288135e+10,1.204421e+10,1.192695e+10,1.289087e+10,1.231978e+10,1.277628e+10,1.322824e+10,1.133526e+10,1.186387e+10
AND,Andorra,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,7.861921e+07,8.940982e+07,1.134082e+08,1.508201e+08,1.865587e+08,2.201272e+08,2.272810e+08,2.540202e+08,3.080089e+08,4.115783e+08,4.464161e+08,3.889587e+08,3.758960e+08,3.278618e+08,3.300707e+08,3.467380e+08,4.820006e+08,6.113164e+08,7.214259e+08,7.954493e+08,1.029048e+09,1.106929e+09,1.210014e+09,1.007026e+09,1.017549e+09,1.178739e+09,1.223945e+09,1.180597e+09,1.211932e+09,1.239876e+09,1.434430e+09,1.496913e+09,1.733117e+09,2.398646e+09,2.935659e+09,3.255789e+09,3.543257e+09,4.016972e+09,4.007353e+09,3.660531e+09,3.355695e+09,3.442063e+09,3.164615e+09,3.281585e+09,3.350736e+09,2.811489e+09,2.858518e+09
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
XKX,Kosovo,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,1.849196e+09,2.535334e+09,2.702427e+09,3.355083e+09,3.639935e+09,3.736600e+09,4.078158e+09,4.833561e+09,5.687488e+09,5.653793e+09,5.829934e+09,6.649291e+09,6.473725e+09,7.072092e+09,7.386891e+09,6.440501e+09,6.649889e+09
YEM,"Yemen, Rep.",NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,5.647252e+09,5.930370e+09,6.463650e+09,5.368271e+09,4.167356e+09,4.258789e+09,5.785685e+09,6.839039e+09,6.325220e+09,7.641101e+09,9.636342e+09,9.854042e+09,1.069328e+10,1.177777e+10,1.387350e+10,1.675377e+10,1.908172e+10,2.165652e+10,2.691085e+10,2.513027e+10,3.090675e+10,3.272642e+10,3.539315e+10,4.041523e+10,4.322858e+10,3.773392e+10,2.731761e+10
ZAF,South Africa,7.575248e+09,7.972841e+09,8.497830e+09,9.423212e+09,1.037379e+10,1.133417e+10,1.235475e+10,1.377712e+10,1.489430e+10,1.678006e+10,1.841803e+10,2.033417e+10,2.135814e+10,2.929395e+10,3.680648e+10,3.811494e+10,3.660189e+10,4.064972e+10,4.673758e+10,5.764727e+10,8.298408e+10,8.962950e+10,8.269690e+10,8.878658e+10,8.788047e+10,6.920845e+10,8.210792e+10,1.074150e+11,1.183315e+11,1.289027e+11,1.155533e+11,1.239434e+11,1.345452e+11,1.343098e+11,1.397525e+11,1.554603e+11,1.476080e+11,1.525862e+11,1.377744e+11,1.366320e+11,1.363619e+11,1.216008e+11,1.157481e+11,1.752569e+11,2.289373e+11,2.576714e+11,2.718111e+11,2.990335e+11,2.871000e+11,2.972167e+11,3.752981e+11,4.168782e+11,3.963326e+11,3.668100e+11,3.511191e+11,3.176107e+11,2.954562e+11
ZMB,Zambia,7.130000e+08,6.962857e+08,6.931429e+08,7.187143e+08,8.394286e+08,1.082857e+09,1.264286e+09,1.368000e+09,1.605857e+09,1.965714e+09,1.825286e+09,1.687000e+09,1.910714e+09,2.268714e+09,3.121833e+09,2.618667e+09,2.746714e+09,2.483000e+09,2.813375e+09,3.325500e+09,3.829500e+09,3.872667e+09,3.994778e+09,3.216308e+09,2.739444e+09,2.281258e+09,1.661949e+09,2.269895e+09,3.713614e+09,3.998638e+09,3.285217e+09,3.378882e+09,3.181922e+09,3.273238e+09,3.656648e+09,3.807067e+09,3.597221e+09,4.303282e+09,3.537683e+09,3.404312e+09,3.600683e+09,4.094481e+09,4.193846e+09,4.901840e+09,6.221078e+09,8.331870e+09,1.275686e+10,1.405696e+10,1.791086e+10,1.532834e+10,2.026556e+10,2.346010e+10,2.550337e+10,2.804546e+10,2.715063e+10,2.115439e+10,2.106399e+10
ZWE,Zimbabwe,1.052990e+09,1.096647e+09,1.117602e+09,1.159512e+09,1.217138e+09,1.311436e+09,1.281750e+09,1.397002e+09,1.479600e+09,1.747999e+09,1.884206e+09,2.178716e+09,2.677729e+09,3.309354e+09,3.982161e+09,4.371301e+09,4.318372e+09,4.364382e+09,4.351600e+09,5.177459e+09,6.678868e+09,8.011374e+09,8.539701e+09,7.764067e+09,6.352126e+09,5.637259e+09,6.217524e+09,6.741215e+09,7.814784e+09,8.286323e+09,8.783817e+09,8.641482e+09,6.751472e+09,6.563813e+09,6.890675e+09,7.111271e+09,8.553147e+09,8.529572e+09,6.401968e+09,6.858013e+09,6.689958e+09,6.777385e+09,6.342116e+09,5.727592e+09,5.805598e+09,5.755215e+09,5.443896e+09,5.291950e+09,4.415703e+09,8.621574e+09,1.014186e+10,1.209845e+10,1.424249e+10,1.545177e+10,1.589105e+10,1.630467e+10,1.661996e+10

In [41]:
wc = pd.read_csv('world_countries.csv')
wc

,Rank,CCA3,Country/Territory,Capital,Continent,2022 Population,2020 Population,2015 Population,2010 Population,2000 Population,1990 Population,1980 Population,1970 Population,Area (km²),Density (per km²),Growth Rate,World Population Percentage
0,36,AFG,Afghanistan,Kabul,Asia,41128771,38972230,33753499,28189672,19542982,10694796,12486631,10752971,652230,63.0587,1.0257,0.52
1,138,ALB,Albania,Tirana,Europe,2842321,2866849,2882481,2913399,3182021,3295066,2941651,2324731,28748,98.8702,0.9957,0.04
2,34,DZA,Algeria,Algiers,Africa,44903225,43451666,39543154,35856344,30774621,25518074,18739378,13795915,2381741,18.8531,1.0164,0.56
3,213,ASM,American Samoa,Pago Pago,Oceania,44273,46189,51368,54849,58230,47818,32886,27075,199,222.4774,0.9831,0.00
4,203,AND,Andorra,Andorra la Vella,Europe,79824,77700,71746,71519,66097,53569,35611,19860,468,170.5641,1.0100,0.00
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
229,226,WLF,Wallis and Futuna,Mata-Utu,Oceania,11572,11655,12182,13142,14723,13454,11315,9377,142,81.4930,0.9953,0.00
230,172,ESH,Western Sahara,El Aaiún,Africa,575986,556048,491824,413296,270375,178529,116775,76371,266000,2.1654,1.0184,0.01
231,46,YEM,Yemen,Sanaa,Asia,33696614,32284046,28516545,24743946,18628700,13375121,9204938,6843607,527968,63.8232,1.0217,0.42
232,63,ZMB,Zambia,Lusaka,Africa,20017675,18927715,16248230,13792086,9891136,7686401,5720438,4281671,752612,26.5976,1.0280,0.25
233,74,ZWE,Zimbabwe,Harare,Africa,16320537,15669666,14154937,12839771,11834676,10113893,7049926,5202918,390757,41.7665,1.0204,0.20

In [51]:
# inne selecja realnie potrzebnych informacji demograficznych (nieużywane)

inna = wc.melt(id_vars=['CCA3', 'Rank', 'Country/Territory', 'Capital', 'Continent', 'Area (km²)', "Density (per km²)", 'Growth Rate', 'World Population Percentage'],
        var_name='Year',
        value_name="Population" )

inna["Year"] = inna["Year"].str.split().str[0]
inna["Year"] = inna["Year"].astype(int)

inna.rename({"Year": "Pop_Year"})

inna

,CCA3,Rank,Country/Territory,Capital,Continent,Area (km²),Density (per km²),Growth Rate,World Population Percentage,Year,Population
0,AFG,36,Afghanistan,Kabul,Asia,652230,63.0587,1.0257,0.52,2022,41128771
1,ALB,138,Albania,Tirana,Europe,28748,98.8702,0.9957,0.04,2022,2842321
2,DZA,34,Algeria,Algiers,Africa,2381741,18.8531,1.0164,0.56,2022,44903225
3,ASM,213,American Samoa,Pago Pago,Oceania,199,222.4774,0.9831,0.00,2022,44273
4,AND,203,Andorra,Andorra la Vella,Europe,468,170.5641,1.0100,0.00,2022,79824
...,...,...,...,...,...,...,...,...,...,...,...
1867,WLF,226,Wallis and Futuna,Mata-Utu,Oceania,142,81.4930,0.9953,0.00,1970,9377
1868,ESH,172,Western Sahara,El Aaiún,Africa,266000,2.1654,1.0184,0.01,1970,76371
1869,YEM,46,Yemen,Sanaa,Asia,527968,63.8232,1.0217,0.42,1970,6843607
1870,ZMB,63,Zambia,Lusaka,Africa,752612,26.5976,1.0280,0.25,1970,4281671
1871,ZWE,74,Zimbabwe,Harare,Africa,390757,41.7665,1.0204,0.20,1970,5202918

In [54]:
## łacznenie 2 nowych plików
newdata = pd.merge(wc, rimland, left_on=['Country/Territory','CCA3'], right_on=['Country Name', 'Country Code'], how='right')
newdata

,Rank,CCA3,Country/Territory,Capital,Continent,2022 Population,2020 Population,2015 Population,2010 Population,2000 Population,1990 Population,1980 Population,1970 Population,Area (km²),Density (per km²),Growth Rate,World Population Percentage,GDP 1960,GDP 1961,GDP 1962,GDP 1963,GDP 1964,GDP 1965,GDP 1966,GDP 1967,GDP 1968,GDP 1969,GDP 1970,GDP 1971,GDP 1972,GDP 1973,GDP 1974,GDP 1975,GDP 1976,GDP 1977,GDP 1978,GDP 1979,GDP 1980,GDP 1981,GDP 1982,GDP 1983,GDP 1984,GDP 1985,GDP 1986,GDP 1987,GDP 1988,GDP 1989,GDP 1990,GDP 1991,GDP 1992,GDP 1993,GDP 1994,GDP 1995,GDP 1996,GDP 1997,GDP 1998,GDP 1999,GDP 2000,GDP 2001,GDP 2002,GDP 2003,GDP 2004,GDP 2005,GDP 2006,GDP 2007,GDP 2008,GDP 2009,GDP 2010,GDP 2011,GDP 2012,GDP 2013,GDP 2014,GDP 2015,GDP 2016
0,198.0,ABW,Aruba,Oranjestad,North America,106445.0,106585.0,104257.0,100341.0,89101.0,65712.0,62267.0,59106.0,180.0,591.3611,0.9991,0.00,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,1.330168e+09,1.320670e+09,1.379888e+09,1.531844e+09,1.665363e+09,1.722799e+09,1.873453e+09,1.920263e+09,1.941095e+09,2.021302e+09,2.228279e+09,2.331006e+09,2.421475e+09,2.623726e+09,2.791961e+09,2.498933e+09,2.467704e+09,2.584464e+09,NaN,NaN,NaN,NaN,NaN
1,36.0,AFG,Afghanistan,Kabul,Asia,41128771.0,38972230.0,33753499.0,28189672.0,19542982.0,10694796.0,12486631.0,10752971.0,652230.0,63.0587,1.0257,0.52,5.377778e+08,5.488889e+08,5.466667e+08,7.511112e+08,8.000000e+08,1.006667e+09,1.400000e+09,1.673333e+09,1.373333e+09,1.408889e+09,1.748887e+09,1.831109e+09,1.595555e+09,1.733333e+09,2.155555e+09,2.366667e+09,2.555556e+09,2.953333e+09,3.300000e+09,3.697940e+09,3.641723e+09,3.478788e+09,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,2.461666e+09,4.128821e+09,4.583644e+09,5.285466e+09,6.275074e+09,7.057598e+09,9.843842e+09,1.019053e+10,1.248694e+10,1.593680e+10,1.793024e+10,2.053654e+10,2.004633e+10,2.005019e+10,1.921556e+10,1.946902e+10
2,42.0,AGO,Angola,Luanda,Africa,35588987.0,33428485.0,28127721.0,23364185.0,16394062.0,11828638.0,8330047.0,6029700.0,1246700.0,28.5466,1.0315,0.45,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,6.684492e+09,6.684492e+09,6.684492e+09,6.684492e+09,1.002674e+10,1.002674e+10,1.211861e+10,5.684292e+09,5.278183e+09,4.059352e+09,5.039552e+09,7.526447e+09,7.648377e+09,6.445042e+09,6.152923e+09,9.129595e+09,8.936064e+09,1.249735e+10,1.418895e+10,1.964085e+10,2.823371e+10,4.178948e+10,6.044892e+10,8.417803e+10,7.549238e+10,8.247091e+10,1.041159e+11,1.153984e+11,1.249121e+11,1.267769e+11,1.029622e+11,9.533511e+10
3,138.0,ALB,Albania,Tirana,Europe,2842321.0,2866849.0,2882481.0,2913399.0,3182021.0,3295066.0,2941651.0,2324731.0,28748.0,98.8702,0.9957,0.04,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,1.924242e+09,1.965385e+09,2.173750e+09,2.156625e+09,2.126000e+09,2.335125e+09,2.101625e+09,1.139167e+09,7.094526e+08,1.228071e+09,1.985674e+09,2.424499e+09,3.314898e+09,2.359903e+09,2.707124e+09,3.414761e+09,3.632044e+09,4.060759e+09,4.435079e+09,5.746946e+09,7.314865e+09,8.158549e+09,8.992642e+09,1.070101e+10,1.288135e+10,1.204421e+10,1.192695e+10,1.289087e+10,1.231978e+10,1.277628e+10,1.322824e+10,1.133526e+10,1.186387e+10
4,203.0,AND,Andorra,Andorra la Vella,Europe,79824.0,77700.0,71746.0,71519.0,66097.0,53569.0,35611.0,19860.0,468.0,170.5641,1.0100,0.00,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,7.861921e+07,8.940982e+07,1.134082e+08,1.508201e+08,1.865587e+08,2.201272e+08,2.272810e+08,2.540202e+08,3.080089e+08,4.115783e+08,4.464161e+08,3.889587e+08,3.758960e+08,3.278618e+08,3.300707e+08,3.467380e+08,4.820006e+08,6.113164e+08,7.214259e+08,7.954493e+08,1.029048e+09,1.106929e+09,1.210014e+09,1.007026e+09,1.017549e+09,1.178739e+09,1.223945e+09,1.180597e+09,1.211932e+09,1.239876e+09,1.434430e+09,1.496913e+09,1.733117e+09,2.398646e+09,2.935659e+09,3.255789e+09,3.543257e+09,4.016972e+09,4.007353e+09,3.660531e+09,3.355695e+09,3.442063e+09,3.164615e+09,3.281585e+09,3.350736e+09,2.811489e+09,2.858518e+09
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
251,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,1.849196e+09,2.535334e+09,2.702427e+09,3.355083e+09,3.639935e+09,3.736600e+09,4.078158e+09,4.833561e+09,5.687488e+09,5.653793e+09,5.829934e+09,6.649291e+09,6.473725e+09,7.072092e+09,7.386891e+09,6.440501e+09,6.649889e+09
252,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,5.647252e+09,5.930370e+09,6.463650e+09,5.368271e+09,4.167356e+09,4.258789e+09,5.785685e+09,6.839039e+09,6.325220e+09,7.641101e+09,9.636342e+09,9.854042e+09,1.069328e+10,1.177777e+10,1.387350e+10,1.675377e+10,1.908172e+10,2.165652e+10,2.691085e+10,2.513027e+10,3.090675e+10,3.272642e+10,3.539315e+10,4.041523e+10,4.322858e+10,3.773392e+10,2.731761e+10
253,24.0,ZAF,South Africa,Pretoria,Africa,59893885.0,58801927.0,55876504.0,51784921.0,46813266.0,39877570.0,29463549.0,22368306.0,1221037.0,49.0517,1.0084,0.75,7.575248e+09,7.972841e+09,8.497830e+09,9.423212e+09,1.037379e+10,1.133417e+10,1.235475e+10,1.377712e+10,1.489430e+10,1.678006e+10,1.841803e+10,2.033417e+10,2.135814e+10,2.929395e+10,3.680648e+10,3.811494e+10,3.660189e+10,4.064972e+10,4.673758e+10,5.764727e+10,8.298408e+10,8.962950e+10,8.269690e+10,8.878658e+10,8.788047e+10,6.920845e+10,8.210792e+10,1.074150e+11,1.183315e+11,1.289027e+11,1.155533e+11,1.239434e+11,1.345452e+11,1.343098e+11,1.397525e+11,1.554603e+11,1.476080e+11,1.525862e+11,1.377744e+11,1.366320e+11,1.363619e+11,1.216008e+11,1.157481e+11,1.752569e+11,2.289373e+11,2.576714e+11,2.718111e+11,2.990335e+11,2.871000e+11,2.972167e+11,3.752981e+11,4.168782e+11,3.963326e+11,3.668100e+11,3.511191e+11,3.176107e+11,2.954562e+11
254,63.0,ZMB,Zambia,Lusaka,Africa,20017675.0,18927715.0,16248230.0,13792086.0,9891136.0,7686401.0,5720438.0,4281671.0,752612.0,26.5976,1.0280,0.25,7.130000e+08,6.962857e+08,6.931429e+08,7.187143e+08,8.394286e+08,1.082857e+09,1.264286e+09,1.368000e+09,1.605857e+09,1.965714e+09,1.825286e+09,1.687000e+09,1.910714e+09,2.268714e+09,3.121833e+09,2.618667e+09,2.746714e+09,2.483000e+09,2.813375e+09,3.325500e+09,3.829500e+09,3.872667e+09,3.994778e+09,3.216308e+09,2.739444e+09,2.281258e+09,1.661949e+09,2.269895e+09,3.713614e+09,3.998638e+09,3.285217e+09,3.378882e+09,3.181922e+09,3.273238e+09,3.656648e+09,3.807067e+09,3.597221e+09,4.303282e+09,3.537683e+09,3.404312e+09,3.600683e+09,4.094481e+09,4.193846e+09,4.901840e+09,6.221078e+09,8.331870e+09,1.275686e+10,1.405696e+10,1.791086e+10,1.532834e+10,2.026556e+10,2.346010e+10,2.550337e+10,2.804546e+10,2.715063e+10,2.115439e+10,2.106399e+10
255,74.0,ZWE,Zimbabwe,Harare,Africa,16320537.0,15669666.0,14154937.0,12839771.0,11834676.0,10113893.0,7049926.0,5202918.0,390757.0,41.7665,1.0204,0.20,1.052990e+09,1.096647e+09,1.117602e+09,1.159512e+09,1.217138e+09,1.311436e+09,1.281750e+09,1.397002e+09,1.479600e+09,1.747999e+09,1.884206e+09,2.178716e+09,2.677729e+09,3.309354e+09,3.982161e+09,4.371301e+09,4.318372e+09,4.364382e+09,4.351600e+09,5.177459e+09,6.678868e+09,8.011374e+09,8.539701e+09,7.764067e+09,6.352126e+09,5.637259e+09,6.217524e+09,6.741215e+09,7.814784e+09,8.286323e+09,8.783817e+09,8.641482e+09,6.751472e+09,6.563813e+09,6.890675e+09,7.111271e+09,8.553147e+09,8.529572e+09,6.401968e+09,6.858013e+09,6.689958e+09,6.777385e+09,6.342116e+09,5.727592e+09,5.805598e+09,5.755215e+09,5.443896e+09,5.291950e+09,4.415703e+09,8.621574e+09,1.014186e+10,1.209845e+10,1.424249e+10,1.545177e+10,1.589105e+10,1.630467e+10,1.661996e+10

In [74]:
################# łączonko
haos = pd.merge(fl, newdata, left_on=['country_name'], right_on=['Country/Territory'])
haos.drop(columns=['Country/Territory'])
haos.to_csv('zad2.2.csv', index=False)
haos

,location_key,country_name,iso_3166_1_alpha_3,population_male,population_female,date,new_tested,new_confirmed,new_deceased,search_trends_cough,search_trends_fever,mobility_retail_and_recreation,mobility_grocery_and_pharmacy,mobility_parks,mobility_transit_stations,mobility_workplaces,mobility_residential,cumulative_confirmed,cumulative_persons_fully_vaccinated,hdi,new_persons_vaccinated,new_persons_fully_vaccinated,adult_male_mortality_rate,adult_female_mortality_rate,new_deceased_age_0,new_deceased_age_1,new_deceased_age_2,new_deceased_age_3,new_deceased_age_4,new_deceased_age_5,new_deceased_age_6,new_deceased_age_7,new_deceased_age_8,new_deceased_age_9,new_confirmed_age_0,new_confirmed_age_1,new_confirmed_age_2,new_confirmed_age_3,new_confirmed_age_4,new_confirmed_age_5,new_confirmed_age_6,new_confirmed_age_7,new_confirmed_age_8,new_confirmed_age_9,new_recovered,new_intensive_care_patients,Rank,CCA3,Country/Territory,Capital,Continent,2022 Population,2020 Population,2015 Population,2010 Population,2000 Population,1990 Population,1980 Population,1970 Population,Area (km²),Density (per km²),Growth Rate,World Population Percentage,GDP 1960,GDP 1961,GDP 1962,GDP 1963,GDP 1964,GDP 1965,GDP 1966,GDP 1967,GDP 1968,GDP 1969,GDP 1970,GDP 1971,GDP 1972,GDP 1973,GDP 1974,GDP 1975,GDP 1976,GDP 1977,GDP 1978,GDP 1979,GDP 1980,GDP 1981,GDP 1982,GDP 1983,GDP 1984,GDP 1985,GDP 1986,GDP 1987,GDP 1988,GDP 1989,GDP 1990,GDP 1991,GDP 1992,GDP 1993,GDP 1994,GDP 1995,GDP 1996,GDP 1997,GDP 1998,GDP 1999,GDP 2000,GDP 2001,GDP 2002,GDP 2003,GDP 2004,GDP 2005,GDP 2006,GDP 2007,GDP 2008,GDP 2009,GDP 2010,GDP 2011,GDP 2012,GDP 2013,GDP 2014,GDP 2015,GDP 2016
0,GB,United Kingdom,GBR,32901036,33746076,2020-12-05,354378,12893,396,4.24,3.35,-36.0,-6.0,-8.0,-41.0,-13.0,8.0,NaN,NaN,NaN,NaN,NaN,NaN,NaN,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,<NA>,<NA>,21.0,GBR,United Kingdom,London,Europe,67508936.0,67059474.0,65224364.0,62760039.0,58850043.0,57210442.0,56326328.0,55650166.0,242900.0,277.9289,1.0034,0.85,7.232805e+10,7.669436e+10,8.060194e+10,8.544377e+10,9.338760e+10,1.005958e+11,1.070907e+11,1.111854e+11,1.047027e+11,1.126769e+11,1.306719e+11,1.481139e+11,1.699650e+11,1.925380e+11,2.061314e+11,2.417566e+11,2.326146e+11,2.630665e+11,3.358830e+11,4.389941e+11,5.649477e+11,5.407657e+11,5.150489e+11,4.896180e+11,4.614871e+11,4.892852e+11,6.014527e+11,7.451626e+11,9.101227e+11,9.268848e+11,1.093169e+12,1.142797e+12,1.179660e+12,1.061389e+12,1.140490e+12,1.335219e+12,1.408782e+12,1.552484e+12,1.638511e+12,1.665624e+12,1.647951e+12,1.621510e+12,1.768408e+12,2.038395e+12,2.398555e+12,2.520702e+12,2.692613e+12,3.074360e+12,2.890564e+12,2.382826e+12,2.441173e+12,2.619700e+12,2.662085e+12,2.739819e+12,3.022828e+12,2.885570e+12,2.647899e+12
1,GB,United Kingdom,GBR,32901036,33746076,2020-07-30,206656,946,10,3.37,4.52,-23.0,-7.0,120.0,-41.0,-48.0,13.0,NaN,NaN,NaN,NaN,NaN,NaN,NaN,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,<NA>,<NA>,21.0,GBR,United Kingdom,London,Europe,67508936.0,67059474.0,65224364.0,62760039.0,58850043.0,57210442.0,56326328.0,55650166.0,242900.0,277.9289,1.0034,0.85,7.232805e+10,7.669436e+10,8.060194e+10,8.544377e+10,9.338760e+10,1.005958e+11,1.070907e+11,1.111854e+11,1.047027e+11,1.126769e+11,1.306719e+11,1.481139e+11,1.699650e+11,1.925380e+11,2.061314e+11,2.417566e+11,2.326146e+11,2.630665e+11,3.358830e+11,4.389941e+11,5.649477e+11,5.407657e+11,5.150489e+11,4.896180e+11,4.614871e+11,4.892852e+11,6.014527e+11,7.451626e+11,9.101227e+11,9.268848e+11,1.093169e+12,1.142797e+12,1.179660e+12,1.061389e+12,1.140490e+12,1.335219e+12,1.408782e+12,1.552484e+12,1.638511e+12,1.665624e+12,1.647951e+12,1.621510e+12,1.768408e+12,2.038395e+12,2.398555e+12,2.520702e+12,2.692613e+12,3.074360e+12,2.890564e+12,2.382826e+12,2.441173e+12,2.619700e+12,2.662085e+12,2.739819e+12,3.022828e+12,2.885570e+12,2.647899e+12
2,GB,United Kingdom,GBR,32901036,33746076,2020-09-13,227075,2154,17,8.06,8.08,-21.0,-12.0,94.0,-24.0,-7.0,1.0,NaN,NaN,NaN,NaN,NaN,NaN,NaN,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,<NA>,<NA>,21.0,GBR,United Kingdom,London,Europe,67508936.0,67059474.0,65224364.0,62760039.0,58850043.0,57210442.0,56326328.0,55650166.0,242900.0,277.9289,1.0034,0.85,7.232805e+10,7.669436e+10,8.060194e+10,8.544377e+10,9.338760e+10,1.005958e+11,1.070907e+11,1.111854e+11,1.047027e+11,1.126769e+11,1.306719e+11,1.481139e+11,1.699650e+11,1.925380e+11,2.061314e+11,2.417566e+11,2.326146e+11,2.630665e+11,3.358830e+11,4.389941e+11,5.649477e+11,5.407657e+11,5.150489e+11,4.896180e+11,4.614871e+11,4.892852e+11,6.014527e+11,7.451626e+11,9.101227e+11,9.268848e+11,1.093169e+12,1.142797e+12,1.179660e+12,1.061389e+12,1.140490e+12,1.335219e+12,1.408782e+12,1.552484e+12,1.638511e+12,1.665624e+12,1.647951e+12,1.621510e+12,1.768408e+12,2.038395e+12,2.398555e+12,2.520702e+12,2.692613e+12,3.074360e+12,2.890564e+12,2.382826e+12,2.441173e+12,2.619700e+12,2.662085e+12,2.739819e+12,3.022828e+12,2.885570e+12,2.647899e+12
3,GB,United Kingdom,GBR,32901036,33746076,2020-07-12,101927,366,14,2.96,3.94,-43.0,-15.0,103.0,-27.0,-10.0,3.0,NaN,NaN,NaN,NaN,NaN,NaN,NaN,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,<NA>,<NA>,21.0,GBR,United Kingdom,London,Europe,67508936.0,67059474.0,65224364.0,62760039.0,58850043.0,57210442.0,56326328.0,55650166.0,242900.0,277.9289,1.0034,0.85,7.232805e+10,7.669436e+10,8.060194e+10,8.544377e+10,9.338760e+10,1.005958e+11,1.070907e+11,1.111854e+11,1.047027e+11,1.126769e+11,1.306719e+11,1.481139e+11,1.699650e+11,1.925380e+11,2.061314e+11,2.417566e+11,2.326146e+11,2.630665e+11,3.358830e+11,4.389941e+11,5.649477e+11,5.407657e+11,5.150489e+11,4.896180e+11,4.614871e+11,4.892852e+11,6.014527e+11,7.451626e+11,9.101227e+11,9.268848e+11,1.093169e+12,1.142797e+12,1.179660e+12,1.061389e+12,1.140490e+12,1.335219e+12,1.408782e+12,1.552484e+12,1.638511e+12,1.665624e+12,1.647951e+12,1.621510e+12,1.768408e+12,2.038395e+12,2.398555e+12,2.520702e+12,2.692613e+12,3.074360e+12,2.890564e+12,2.382826e+12,2.441173e+12,2.619700e+12,2.662085e+12,2.739819e+12,3.022828e+12,2.885570e+12,2.647899e+12
4,GB,United Kingdom,GBR,32901036,33746076,2020-11-11,381759,27757,392,5.15,5.15,-49.0,-14.0,-1.0,-51.0,-38.0,16.0,NaN,NaN,NaN,NaN,NaN,NaN,NaN,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,<NA>,<NA>,21.0,GBR,United Kingdom,London,Europe,67508936.0,67059474.0,65224364.0,62760039.0,58850043.0,57210442.0,56326328.0,55650166.0,242900.0,277.9289,1.0034,0.85,7.232805e+10,7.669436e+10,8.060194e+10,8.544377e+10,9.338760e+10,1.005958e+11,1.070907e+11,1.111854e+11,1.047027e+11,1.126769e+11,1.306719e+11,1.481139e+11,1.699650e+11,1.925380e+11,2.061314e+11,2.417566e+11,2.326146e+11,2.630665e+11,3.358830e+11,4.389941e+11,5.649477e+11,5.407657e+11,5.150489e+11,4.896180e+11,4.614871e+11,4.892852e+11,6.014527e+11,7.451626e+11,9.101227e+11,9.268848e+11,1.093169e+12,1.142797e+12,1.179660e+12,1.061389e+12,1.140490e+12,1.335219e+12,1.408782e+12,1.552484e+12,1.638511e+12,1.665624e+12,1.647951e+12,1.621510e+12,1.768408e+12,2.038395e+12,2.398555e+12,2.520702e+12,2.692613e+12,3.074360e+12,2.890564e+12,2.382826e+12,2.441173e+12,2.619700e+12,2.662085e+12,2.739819e+12,3.022828e+12,2.885570e+12,2.647899e+12
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
704,AU,Australia,AUS,12698625,12801256,2020-12-20,46358,44,0,5.51,4.40,-2.0,6.0,-8.0,-30.0,-3.0,1.0,28172.0,0.0,0.939,NaN,NaN,NaN,NaN,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,<NA>,<NA>,55.0,AUS,Australia,Canberra,Oceania,26177413.0,25670051.0,23820236.0,22019168.0,19017963.0,17048003.0,14706322.0,12595034.0,7692024.0,3.4032,1.0099,0.33,1.859335e+10,1.966626e+10,1.991152e+10,2.152761e+10,2.378766e+10,2.596259e+10,2.728861e+10,3.042110e+10,3.268787e+10,3.665920e+10,4.130474e+10,4.518311e+10,5.200350e+10,6.378219e+10,8.890641e+10,9.722655e+10,1.049742e+11,1.102661e+11,1.184006e+11,1.347938e+11,1.498875e+11,1.768048e+11,1.939545e+11,1.771764e+11,1.935039e+11,1.804710e+11,1.822818e+11,1.893760e+11,2.361358e+11,2.999414e+11,3.114259e+11,3.260686e+11,3.256925e+11,3.123728e+11,3.232169e+11,3.683917e+11,4.018194e+11,4.360980e+11,3.997789e+11,3.891465e+11,4.154462e+11,3.788999e+11,3.946358e+11,4.668532e+11,6.133298e+11,6.937641e+11,7.475726e+11,8.537646e+11,1.055335e+12,9.271683e+11,1.142877e+12,1.390557e+12,1.538194e+12,1.567179e+12,1.459598e+12,1.345383e+12,1.204616e+12
705,AU,Australia,AUS,12698625,12801256,2020-11-09,29026,10,0,5.91,5.61,-12.0,0.0,-15.0,-41.0,-9.0,5.0,27668.0,0.0,0.939,NaN,NaN,NaN,NaN,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,<NA>,<NA>,55.0,AUS,Australia,Canberra,Oceania,26177413.0,25670051.0,23820236.0,22019168.0,19017963.0,17048003.0,14706322.0,12595034.0,7692024.0,3.4032,1.0099,0.33,1.859335e+10,1.966626e+10,1.991152e+10,2.152761e+10,2.378766e+10,2.596259e+10,2.728861e+10,3.042110e+10,3.268787e+10,3.665920e+10,4.130474e+10,4.518311e+10,5.200350e+10,6.378219e+10,8.890641e+10,9.722655e+10,1.049742e+11,1.102661e+11,1.184006e+11,1.347938e+11,1.498875e+11,1.768048e+11,1.939545e+11,1.771764e+11,1.935039e+11,1.804710e+11,1.822818e+11,1.893760e+11,2.361358e+11,2.999414e+11,3.114259e+11,3.260686e+11,3.256925e+11,3.123728e+11,3.232169e+11,3.683917e+11,4.018194e+11,4.360980e+11,3.997789e+11,3.891465e+11,4.154462e+11,3.788999e+11,3.946358e+11,4.668532e+11,6.133298e+11,6.937641e+11,7.475726e+11,8.537646e+11,1.055335e+12,9.271683e+11,1.142877e+12,1.390557e+12,1.538194e+12,1.567179e+12,1.459598e+12,1.345383e+12,1.204616e+12
706,AU,Australia,AUS,12698625,12801256,2020-08-06,89981,483,8,5.85,5.36,-23.0,-8.0,-10.0,-46.0,-22.0,12.0,19863.0,0.0,0.939,NaN,NaN,NaN,NaN,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,<NA>,<NA>,55.0,AUS,Australia,Canberra,Oceania,26177413.0,25670051.0,23820236.0,22019168.0,19017963.0,17048003.0,14706322.0,12595034.0,7692024.0,3.4032,1.0099,0.33,1.859335e+10,1.966626e+10,1.991152e+10,2.152761e+10,2.378766e+10,2.596259e+10,2.728861e+10,3.042110e+10,3.268787e+10,3.665920e+10,4.130474e+10,4.518311e+10,5.200350e+10,6.378219e+10,8.890641e+10,9.722655e+10,1.049742e+11,1.102661e+11,1.184006e+11,1.347938e+11,1.498875e+11,1.768048e+11,1.939545e+11,1.771764e+11,1.935039e+11,1.804710e+11,1.822818e+11,1.893760e+11,2.361358e+11,2.999414e+11,3.114259e+11,3.260686e+11,3.256925e+11,3.123728e+11,3.232169e+11,3.683917e+11,4.018194e+11,4.360980e+11,3.997789e+11,3.891465e+11,4.154462e+11,3.788999e+11,3.946358e+11,4.668532e+11,6.133298e+11,6.937641e+11,7.475726e+11,8.537646e+11,1.055335e+12,9.271683e+11,1.142877e+12,1.390557e+12,1.538194e+12,1.567179e+12,1.459598e+12,1.345383e+12,1.204616e+12
707,AU,Australia,AUS,12698625,12801256,2020-07-25,64084,372,5,5.33,4.53,-15.0,-2.0,-15.0,-39.0,-11.0,8.0,13950.0,0.0,0.939,NaN,NaN,NaN,NaN,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,<NA>,<NA>,55.0,AUS,Australia,Canberra,Oceania,26177413.0,25670051.0,23820236.0,22019168.0,19017963.0,17048003.0,14706322.0,12595034.0,7692024.0,3.4032,1.0099,0.33,1.859335e+10,1.966626e+10,1.991152e+10,2.152761e+10,2.378766e+10,2.596259e+10,2.728861e+10,3.042110e+10,3.268787e+10,3.665920e+10,4.130474e+10,4.518311e+10,5.200350e+10,6.378219e+10,8.890641e+10,9.722655e+10,1.049742e+11,1.102661e+11,1.184006e+11,1.347938e+11,1.498875e+11,1.768048e+11,1.939545e+11,1.771764e+11,1.935039e+11,1.804710e+11,1.822818e+11,1.893760e+11,2.361358e+11,2.999414e+11,3.114259e+11,3.260686e+11,3.256925e+11,3.123728e+11,3.232169e+11,3.683917e+11,4.018194e+11,4.360980e+11,3.997789e+11,3.891465e+11,4.154462e+11,3.788999e+11,3.946358e+11,4.668532e+11,6.133298e+11,6.937641e+11,7.475726e+11,8.537646e+11,1.055335e+12,9.271683e+11,1.142877e+12,1.390557e+12,1.538194e+12,1.567179e+12,1.459598e+12,1.345383e+12,1.204616e+12
708,AU,Australia,AUS,12698625,12801256,2020-07-24,75584,309,7,5.53,4.54,-15.0,1.0,-17.0,-41.0,-16.0,10.0,13595.0,0.0,0.939,NaN,NaN,NaN,NaN,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,<NA>,<NA>,55.0,AUS,Australia,Canberra,Oceania,26177413.0,25670051.0,23820236.0,22019168.0,19017963.0,17048003.0,14706322.0,12595034.0,7692024.0,3.4032,1.0099,0.33,1.859335e+10,1.966626e+10,1.991152e+10,2.152761e+10,2.378766e+10,2.596259e+10,2.728861e+10,3.042110e+10,3.268787e+10,3.665920e+10,4.130474e+10,4.518311e+10,5.200350e+10,6.378219e+10,8.890641e+10,9.722655e+10,1.049742e+11,1.102661e+11,1.184006e+11,1.347938e+11,1.498875e+11,1.768048e+11,1.939545e+11,1.771764e+11,1.935039e+11,1.804710e+11,1.822818e+11,1.893760e+11,2.361358e+11,2.999414e+11,3.114259e+11,3.260686e+11,3.256925e+11,3.123728e+11,3.232169e+11,3.683917e+11,4.018194e+11,4.360980e+11,3.997789e+11,3.891465e+11,4.154462e+11,3.788999e+11,3.946358e+11,4.668532e+11,6.133298e+11,6.937641e+11,7.475726e+11,8.537646e+11,1.055335e+12,9.271683e+11,1.142877e+12,1.390557e+12,1.538194e+12,1.567179e+12,1.459598e+12,1.345383e+12,1.204616e+12

# Część 3

In [81]:
# inflacja (interesuje nas tylko 3 lata przed wybuchem pandemi)
inflacja = pd.read_csv('inflation.csv').drop(columns=['Indicator Type', 'Series Name', 'IMF Country Code', 'Unnamed: 59', 'Unnamed: 60', 'Unnamed: 61', 'Unnamed: 62', 'Unnamed: 63', 'Note'])
inflacja = inflacja.drop(inflacja.iloc[:, 2:49], axis=1)
#inflacja
inflacja = inflacja[['Country Code', '2017', '2018', '2019']]
            .add_prefix("inflation ")
            .groupby('inflation Country Code').max()
inflacja

                        inflation 2017  inflation 2018  inflation 2019
inflation Country Code
ABW                               0.66            7.45           12.82
AFG                               6.94            1.47            3.79
AGO                              40.99           22.35           17.71
ALB                               3.91            2.80            2.91
ARE                               1.97            3.54           -1.39
...                                ...             ...             ...
XXK                               1.49            1.05            2.68
YEM                              30.40           27.60           10.00
ZAF                               6.95            5.45            5.21
ZMB                              10.90           11.31           10.44
ZWE                               2.50           14.59          255.29

[206 rows x 3 columns]

In [85]:
alpha = pd.merge(haos, inflacja,
         left_on=['CCA3'],
         right_on=['inflation Country Code'],
         how='inner')
alpha

,location_key,country_name,iso_3166_1_alpha_3,population_male,population_female,date,new_tested,new_confirmed,new_deceased,search_trends_cough,search_trends_fever,mobility_retail_and_recreation,mobility_grocery_and_pharmacy,mobility_parks,mobility_transit_stations,mobility_workplaces,mobility_residential,cumulative_confirmed,cumulative_persons_fully_vaccinated,hdi,new_persons_vaccinated,new_persons_fully_vaccinated,adult_male_mortality_rate,adult_female_mortality_rate,new_deceased_age_0,new_deceased_age_1,new_deceased_age_2,new_deceased_age_3,new_deceased_age_4,new_deceased_age_5,new_deceased_age_6,new_deceased_age_7,new_deceased_age_8,new_deceased_age_9,new_confirmed_age_0,new_confirmed_age_1,new_confirmed_age_2,new_confirmed_age_3,new_confirmed_age_4,new_confirmed_age_5,new_confirmed_age_6,new_confirmed_age_7,new_confirmed_age_8,new_confirmed_age_9,new_recovered,new_intensive_care_patients,Rank,CCA3,Country/Territory,Capital,Continent,2022 Population,2020 Population,2015 Population,2010 Population,2000 Population,1990 Population,1980 Population,1970 Population,Area (km²),Density (per km²),Growth Rate,World Population Percentage,GDP 1960,GDP 1961,GDP 1962,GDP 1963,GDP 1964,GDP 1965,GDP 1966,GDP 1967,GDP 1968,GDP 1969,GDP 1970,GDP 1971,GDP 1972,GDP 1973,GDP 1974,GDP 1975,GDP 1976,GDP 1977,GDP 1978,GDP 1979,GDP 1980,GDP 1981,GDP 1982,GDP 1983,GDP 1984,GDP 1985,GDP 1986,GDP 1987,GDP 1988,GDP 1989,GDP 1990,GDP 1991,GDP 1992,GDP 1993,GDP 1994,GDP 1995,GDP 1996,GDP 1997,GDP 1998,GDP 1999,GDP 2000,GDP 2001,GDP 2002,GDP 2003,GDP 2004,GDP 2005,GDP 2006,GDP 2007,GDP 2008,GDP 2009,GDP 2010,GDP 2011,GDP 2012,GDP 2013,GDP 2014,GDP 2015,GDP 2016,inflation 2017,inflation 2018,inflation 2019
0,GB,United Kingdom,GBR,32901036,33746076,2020-12-05,354378,12893,396,4.24,3.35,-36.0,-6.0,-8.0,-41.0,-13.0,8.0,NaN,NaN,NaN,NaN,NaN,NaN,NaN,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,<NA>,<NA>,21.0,GBR,United Kingdom,London,Europe,67508936.0,67059474.0,65224364.0,62760039.0,58850043.0,57210442.0,56326328.0,55650166.0,242900.0,277.9289,1.0034,0.85,7.232805e+10,7.669436e+10,8.060194e+10,8.544377e+10,9.338760e+10,1.005958e+11,1.070907e+11,1.111854e+11,1.047027e+11,1.126769e+11,1.306719e+11,1.481139e+11,1.699650e+11,1.925380e+11,2.061314e+11,2.417566e+11,2.326146e+11,2.630665e+11,3.358830e+11,4.389941e+11,5.649477e+11,5.407657e+11,5.150489e+11,4.896180e+11,4.614871e+11,4.892852e+11,6.014527e+11,7.451626e+11,9.101227e+11,9.268848e+11,1.093169e+12,1.142797e+12,1.179660e+12,1.061389e+12,1.140490e+12,1.335219e+12,1.408782e+12,1.552484e+12,1.638511e+12,1.665624e+12,1.647951e+12,1.621510e+12,1.768408e+12,2.038395e+12,2.398555e+12,2.520702e+12,2.692613e+12,3.074360e+12,2.890564e+12,2.382826e+12,2.441173e+12,2.619700e+12,2.662085e+12,2.739819e+12,3.022828e+12,2.885570e+12,2.647899e+12,6.11,3.70,10.93
1,GB,United Kingdom,GBR,32901036,33746076,2020-07-30,206656,946,10,3.37,4.52,-23.0,-7.0,120.0,-41.0,-48.0,13.0,NaN,NaN,NaN,NaN,NaN,NaN,NaN,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,<NA>,<NA>,21.0,GBR,United Kingdom,London,Europe,67508936.0,67059474.0,65224364.0,62760039.0,58850043.0,57210442.0,56326328.0,55650166.0,242900.0,277.9289,1.0034,0.85,7.232805e+10,7.669436e+10,8.060194e+10,8.544377e+10,9.338760e+10,1.005958e+11,1.070907e+11,1.111854e+11,1.047027e+11,1.126769e+11,1.306719e+11,1.481139e+11,1.699650e+11,1.925380e+11,2.061314e+11,2.417566e+11,2.326146e+11,2.630665e+11,3.358830e+11,4.389941e+11,5.649477e+11,5.407657e+11,5.150489e+11,4.896180e+11,4.614871e+11,4.892852e+11,6.014527e+11,7.451626e+11,9.101227e+11,9.268848e+11,1.093169e+12,1.142797e+12,1.179660e+12,1.061389e+12,1.140490e+12,1.335219e+12,1.408782e+12,1.552484e+12,1.638511e+12,1.665624e+12,1.647951e+12,1.621510e+12,1.768408e+12,2.038395e+12,2.398555e+12,2.520702e+12,2.692613e+12,3.074360e+12,2.890564e+12,2.382826e+12,2.441173e+12,2.619700e+12,2.662085e+12,2.739819e+12,3.022828e+12,2.885570e+12,2.647899e+12,6.11,3.70,10.93
2,GB,United Kingdom,GBR,32901036,33746076,2020-09-13,227075,2154,17,8.06,8.08,-21.0,-12.0,94.0,-24.0,-7.0,1.0,NaN,NaN,NaN,NaN,NaN,NaN,NaN,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,<NA>,<NA>,21.0,GBR,United Kingdom,London,Europe,67508936.0,67059474.0,65224364.0,62760039.0,58850043.0,57210442.0,56326328.0,55650166.0,242900.0,277.9289,1.0034,0.85,7.232805e+10,7.669436e+10,8.060194e+10,8.544377e+10,9.338760e+10,1.005958e+11,1.070907e+11,1.111854e+11,1.047027e+11,1.126769e+11,1.306719e+11,1.481139e+11,1.699650e+11,1.925380e+11,2.061314e+11,2.417566e+11,2.326146e+11,2.630665e+11,3.358830e+11,4.389941e+11,5.649477e+11,5.407657e+11,5.150489e+11,4.896180e+11,4.614871e+11,4.892852e+11,6.014527e+11,7.451626e+11,9.101227e+11,9.268848e+11,1.093169e+12,1.142797e+12,1.179660e+12,1.061389e+12,1.140490e+12,1.335219e+12,1.408782e+12,1.552484e+12,1.638511e+12,1.665624e+12,1.647951e+12,1.621510e+12,1.768408e+12,2.038395e+12,2.398555e+12,2.520702e+12,2.692613e+12,3.074360e+12,2.890564e+12,2.382826e+12,2.441173e+12,2.619700e+12,2.662085e+12,2.739819e+12,3.022828e+12,2.885570e+12,2.647899e+12,6.11,3.70,10.93
3,GB,United Kingdom,GBR,32901036,33746076,2020-07-12,101927,366,14,2.96,3.94,-43.0,-15.0,103.0,-27.0,-10.0,3.0,NaN,NaN,NaN,NaN,NaN,NaN,NaN,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,<NA>,<NA>,21.0,GBR,United Kingdom,London,Europe,67508936.0,67059474.0,65224364.0,62760039.0,58850043.0,57210442.0,56326328.0,55650166.0,242900.0,277.9289,1.0034,0.85,7.232805e+10,7.669436e+10,8.060194e+10,8.544377e+10,9.338760e+10,1.005958e+11,1.070907e+11,1.111854e+11,1.047027e+11,1.126769e+11,1.306719e+11,1.481139e+11,1.699650e+11,1.925380e+11,2.061314e+11,2.417566e+11,2.326146e+11,2.630665e+11,3.358830e+11,4.389941e+11,5.649477e+11,5.407657e+11,5.150489e+11,4.896180e+11,4.614871e+11,4.892852e+11,6.014527e+11,7.451626e+11,9.101227e+11,9.268848e+11,1.093169e+12,1.142797e+12,1.179660e+12,1.061389e+12,1.140490e+12,1.335219e+12,1.408782e+12,1.552484e+12,1.638511e+12,1.665624e+12,1.647951e+12,1.621510e+12,1.768408e+12,2.038395e+12,2.398555e+12,2.520702e+12,2.692613e+12,3.074360e+12,2.890564e+12,2.382826e+12,2.441173e+12,2.619700e+12,2.662085e+12,2.739819e+12,3.022828e+12,2.885570e+12,2.647899e+12,6.11,3.70,10.93
4,GB,United Kingdom,GBR,32901036,33746076,2020-11-11,381759,27757,392,5.15,5.15,-49.0,-14.0,-1.0,-51.0,-38.0,16.0,NaN,NaN,NaN,NaN,NaN,NaN,NaN,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,<NA>,<NA>,21.0,GBR,United Kingdom,London,Europe,67508936.0,67059474.0,65224364.0,62760039.0,58850043.0,57210442.0,56326328.0,55650166.0,242900.0,277.9289,1.0034,0.85,7.232805e+10,7.669436e+10,8.060194e+10,8.544377e+10,9.338760e+10,1.005958e+11,1.070907e+11,1.111854e+11,1.047027e+11,1.126769e+11,1.306719e+11,1.481139e+11,1.699650e+11,1.925380e+11,2.061314e+11,2.417566e+11,2.326146e+11,2.630665e+11,3.358830e+11,4.389941e+11,5.649477e+11,5.407657e+11,5.150489e+11,4.896180e+11,4.614871e+11,4.892852e+11,6.014527e+11,7.451626e+11,9.101227e+11,9.268848e+11,1.093169e+12,1.142797e+12,1.179660e+12,1.061389e+12,1.140490e+12,1.335219e+12,1.408782e+12,1.552484e+12,1.638511e+12,1.665624e+12,1.647951e+12,1.621510e+12,1.768408e+12,2.038395e+12,2.398555e+12,2.520702e+12,2.692613e+12,3.074360e+12,2.890564e+12,2.382826e+12,2.441173e+12,2.619700e+12,2.662085e+12,2.739819e+12,3.022828e+12,2.885570e+12,2.647899e+12,6.11,3.70,10.93
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
704,AU,Australia,AUS,12698625,12801256,2020-12-20,46358,44,0,5.51,4.40,-2.0,6.0,-8.0,-30.0,-3.0,1.0,28172.0,0.0,0.939,NaN,NaN,NaN,NaN,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,<NA>,<NA>,55.0,AUS,Australia,Canberra,Oceania,26177413.0,25670051.0,23820236.0,22019168.0,19017963.0,17048003.0,14706322.0,12595034.0,7692024.0,3.4032,1.0099,0.33,1.859335e+10,1.966626e+10,1.991152e+10,2.152761e+10,2.378766e+10,2.596259e+10,2.728861e+10,3.042110e+10,3.268787e+10,3.665920e+10,4.130474e+10,4.518311e+10,5.200350e+10,6.378219e+10,8.890641e+10,9.722655e+10,1.049742e+11,1.102661e+11,1.184006e+11,1.347938e+11,1.498875e+11,1.768048e+11,1.939545e+11,1.771764e+11,1.935039e+11,1.804710e+11,1.822818e+11,1.893760e+11,2.361358e+11,2.999414e+11,3.114259e+11,3.260686e+11,3.256925e+11,3.123728e+11,3.232169e+11,3.683917e+11,4.018194e+11,4.360980e+11,3.997789e+11,3.891465e+11,4.154462e+11,3.788999e+11,3.946358e+11,4.668532e+11,6.133298e+11,6.937641e+11,7.475726e+11,8.537646e+11,1.055335e+12,9.271683e+11,1.142877e+12,1.390557e+12,1.538194e+12,1.567179e+12,1.459598e+12,1.345383e+12,1.204616e+12,8.49,5.21,4.48
705,AU,Australia,AUS,12698625,12801256,2020-11-09,29026,10,0,5.91,5.61,-12.0,0.0,-15.0,-41.0,-9.0,5.0,27668.0,0.0,0.939,NaN,NaN,NaN,NaN,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,<NA>,<NA>,55.0,AUS,Australia,Canberra,Oceania,26177413.0,25670051.0,23820236.0,22019168.0,19017963.0,17048003.0,14706322.0,12595034.0,7692024.0,3.4032,1.0099,0.33,1.859335e+10,1.966626e+10,1.991152e+10,2.152761e+10,2.378766e+10,2.596259e+10,2.728861e+10,3.042110e+10,3.268787e+10,3.665920e+10,4.130474e+10,4.518311e+10,5.200350e+10,6.378219e+10,8.890641e+10,9.722655e+10,1.049742e+11,1.102661e+11,1.184006e+11,1.347938e+11,1.498875e+11,1.768048e+11,1.939545e+11,1.771764e+11,1.935039e+11,1.804710e+11,1.822818e+11,1.893760e+11,2.361358e+11,2.999414e+11,3.114259e+11,3.260686e+11,3.256925e+11,3.123728e+11,3.232169e+11,3.683917e+11,4.018194e+11,4.360980e+11,3.997789e+11,3.891465e+11,4.154462e+11,3.788999e+11,3.946358e+11,4.668532e+11,6.133298e+11,6.937641e+11,7.475726e+11,8.537646e+11,1.055335e+12,9.271683e+11,1.142877e+12,1.390557e+12,1.538194e+12,1.567179e+12,1.459598e+12,1.345383e+12,1.204616e+12,8.49,5.21,4.48
706,AU,Australia,AUS,12698625,12801256,2020-08-06,89981,483,8,5.85,5.36,-23.0,-8.0,-10.0,-46.0,-22.0,12.0,19863.0,0.0,0.939,NaN,NaN,NaN,NaN,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,<NA>,<NA>,55.0,AUS,Australia,Canberra,Oceania,26177413.0,25670051.0,23820236.0,22019168.0,19017963.0,17048003.0,14706322.0,12595034.0,7692024.0,3.4032,1.0099,0.33,1.859335e+10,1.966626e+10,1.991152e+10,2.152761e+10,2.378766e+10,2.596259e+10,2.728861e+10,3.042110e+10,3.268787e+10,3.665920e+10,4.130474e+10,4.518311e+10,5.200350e+10,6.378219e+10,8.890641e+10,9.722655e+10,1.049742e+11,1.102661e+11,1.184006e+11,1.347938e+11,1.498875e+11,1.768048e+11,1.939545e+11,1.771764e+11,1.935039e+11,1.804710e+11,1.822818e+11,1.893760e+11,2.361358e+11,2.999414e+11,3.114259e+11,3.260686e+11,3.256925e+11,3.123728e+11,3.232169e+11,3.683917e+11,4.018194e+11,4.360980e+11,3.997789e+11,3.891465e+11,4.154462e+11,3.788999e+11,3.946358e+11,4.668532e+11,6.133298e+11,6.937641e+11,7.475726e+11,8.537646e+11,1.055335e+12,9.271683e+11,1.142877e+12,1.390557e+12,1.538194e+12,1.567179e+12,1.459598e+12,1.345383e+12,1.204616e+12,8.49,5.21,4.48
707,AU,Australia,AUS,12698625,12801256,2020-07-25,64084,372,5,5.33,4.53,-15.0,-2.0,-15.0,-39.0,-11.0,8.0,13950.0,0.0,0.939,NaN,NaN,NaN,NaN,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,<NA>,<NA>,55.0,AUS,Australia,Canberra,Oceania,26177413.0,25670051.0,23820236.0,22019168.0,19017963.0,17048003.0,14706322.0,12595034.0,7692024.0,3.4032,1.0099,0.33,1.859335e+10,1.966626e+10,1.991152e+10,2.152761e+10,2.378766e+10,2.596259e+10,2.728861e+10,3.042110e+10,3.268787e+10,3.665920e+10,4.130474e+10,4.518311e+10,5.200350e+10,6.378219e+10,8.890641e+10,9.722655e+10,1.049742e+11,1.102661e+11,1.184006e+11,1.347938e+11,1.498875e+11,1.768048e+11,1.939545e+11,1.771764e+11,1.935039e+11,1.804710e+11,1.822818e+11,1.893760e+11,2.361358e+11,2.999414e+11,3.114259e+11,3.260686e+11,3.256925e+11,3.123728e+11,3.232169e+11,3.683917e+11,4.018194e+11,4.360980e+11,3.997789e+11,3.891465e+11,4.154462e+11,3.788999e+11,3.946358e+11,4.668532e+11,6.133298e+11,6.937641e+11,7.475726e+11,8.537646e+11,1.055335e+12,9.271683e+11,1.142877e+12,1.390557e+12,1.538194e+12,1.567179e+12,1.459598e+12,1.345383e+12,1.204616e+12,8.49,5.21,4.48
708,AU,Australia,AUS,12698625,12801256,2020-07-24,75584,309,7,5.53,4.54,-15.0,1.0,-17.0,-41.0,-16.0,10.0,13595.0,0.0,0.939,NaN,NaN,NaN,NaN,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,<NA>,<NA>,55.0,AUS,Australia,Canberra,Oceania,26177413.0,25670051.0,23820236.0,22019168.0,19017963.0,17048003.0,14706322.0,12595034.0,7692024.0,3.4032,1.0099,0.33,1.859335e+10,1.966626e+10,1.991152e+10,2.152761e+10,2.378766e+10,2.596259e+10,2.728861e+10,3.042110e+10,3.268787e+10,3.665920e+10,4.130474e+10,4.518311e+10,5.200350e+10,6.378219e+10,8.890641e+10,9.722655e+10,1.049742e+11,1.102661e+11,1.184006e+11,1.347938e+11,1.498875e+11,1.768048e+11,1.939545e+11,1.771764e+11,1.935039e+11,1.804710e+11,1.822818e+11,1.893760e+11,2.361358e+11,2.999414e+11,3.114259e+11,3.260686e+11,3.256925e+11,3.123728e+11,3.232169e+11,3.683917e+11,4.018194e+11,4.360980e+11,3.997789e+11,3.891465e+11,4.154462e+11,3.788999e+11,3.946358e+11,4.668532e+11,6.133298e+11,6.937641e+11,7.475726e+11,8.537646e+11,1.055335e+12,9.271683e+11,1.142877e+12,1.390557e+12,1.538194e+12,1.567179e+12,1.459598e+12,1.345383e+12,1.204616e+12,8.49,5.21,4.48

In [91]:
# zanieczyszczenia 

pollution = pd.read_csv("pollution.csv")
pollution
vals = ['Global', 'International Transport']
pollution = pollution[pollution.Country.isin(vals) == False]
pollution

,Unnamed: 0,Country,ISO 3166-1 alpha-3,Year,Total,Coal,Oil,Gas,Cement,Flaring,Other,Per Capita
0,266,Afghanistan,AFG,2016,9.067598,2.878736,5.794097,0.318639,0.076126,0.0,NaN,0.261795
1,267,Afghanistan,AFG,2017,9.867969,3.447824,6.074912,0.300448,0.044785,0.0,NaN,0.276852
2,268,Afghanistan,AFG,2018,10.818048,3.847200,6.620848,0.293120,0.056880,0.0,NaN,0.294876
3,269,Afghanistan,AFG,2019,11.081621,3.954767,6.842956,0.245569,0.038329,0.0,NaN,0.293401
4,270,Afghanistan,AFG,2020,11.681766,4.150072,7.219776,0.251244,0.060674,0.0,NaN,0.299746
...,...,...,...,...,...,...,...,...,...,...,...,...
1375,62555,Zimbabwe,ZWE,2017,9.596071,5.900452,3.226752,0.000000,0.468867,0.0,NaN,0.650533
1376,62556,Zimbabwe,ZWE,2018,11.795478,7.177776,4.059712,0.000000,0.557990,0.0,NaN,0.783639
1377,62557,Zimbabwe,ZWE,2019,11.114607,6.888320,3.656672,0.000000,0.569615,0.0,NaN,0.723861
1378,62558,Zimbabwe,ZWE,2020,10.607897,6.721571,3.316712,0.000000,0.569615,0.0,NaN,0.676970
1379,62559,Zimbabwe,ZWE,2021,11.296114,7.225620,3.500879,0.000000,0.569615,0.0,NaN,0.706293

In [93]:
beta = pd.merge(alpha, pollution,
         left_on=['CCA3'],
         right_on=['ISO 3166-1 alpha-3'],
         how='inner')

beta

,location_key,country_name,iso_3166_1_alpha_3,population_male,population_female,date,new_tested,new_confirmed,new_deceased,search_trends_cough,search_trends_fever,mobility_retail_and_recreation,mobility_grocery_and_pharmacy,mobility_parks,mobility_transit_stations,mobility_workplaces,mobility_residential,cumulative_confirmed,cumulative_persons_fully_vaccinated,hdi,new_persons_vaccinated,new_persons_fully_vaccinated,adult_male_mortality_rate,adult_female_mortality_rate,new_deceased_age_0,new_deceased_age_1,new_deceased_age_2,new_deceased_age_3,new_deceased_age_4,new_deceased_age_5,new_deceased_age_6,new_deceased_age_7,new_deceased_age_8,new_deceased_age_9,new_confirmed_age_0,new_confirmed_age_1,new_confirmed_age_2,new_confirmed_age_3,new_confirmed_age_4,new_confirmed_age_5,new_confirmed_age_6,new_confirmed_age_7,new_confirmed_age_8,new_confirmed_age_9,new_recovered,new_intensive_care_patients,Rank,CCA3,Country/Territory,Capital,Continent,2022 Population,2020 Population,2015 Population,2010 Population,2000 Population,1990 Population,1980 Population,1970 Population,Area (km²),Density (per km²),Growth Rate,World Population Percentage,GDP 1960,GDP 1961,GDP 1962,GDP 1963,GDP 1964,GDP 1965,GDP 1966,GDP 1967,GDP 1968,GDP 1969,GDP 1970,GDP 1971,GDP 1972,GDP 1973,GDP 1974,GDP 1975,GDP 1976,GDP 1977,GDP 1978,GDP 1979,GDP 1980,GDP 1981,GDP 1982,GDP 1983,GDP 1984,GDP 1985,GDP 1986,GDP 1987,GDP 1988,GDP 1989,GDP 1990,GDP 1991,GDP 1992,GDP 1993,GDP 1994,GDP 1995,GDP 1996,GDP 1997,GDP 1998,GDP 1999,GDP 2000,GDP 2001,GDP 2002,GDP 2003,GDP 2004,GDP 2005,GDP 2006,GDP 2007,GDP 2008,GDP 2009,GDP 2010,GDP 2011,GDP 2012,GDP 2013,GDP 2014,GDP 2015,GDP 2016,inflation 2017,inflation 2018,inflation 2019,Unnamed: 0,Country,ISO 3166-1 alpha-3,Year,Total,Coal,Oil,Gas,Cement,Flaring,Other,Per Capita
0,GB,United Kingdom,GBR,32901036,33746076,2020-12-05,354378,12893,396,4.24,3.35,-36.0,-6.0,-8.0,-41.0,-13.0,8.0,NaN,NaN,NaN,NaN,NaN,NaN,NaN,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,<NA>,<NA>,21.0,GBR,United Kingdom,London,Europe,67508936.0,67059474.0,65224364.0,62760039.0,58850043.0,57210442.0,56326328.0,55650166.0,242900.0,277.9289,1.0034,0.85,7.232805e+10,7.669436e+10,8.060194e+10,8.544377e+10,9.338760e+10,1.005958e+11,1.070907e+11,1.111854e+11,1.047027e+11,1.126769e+11,1.306719e+11,1.481139e+11,1.699650e+11,1.925380e+11,2.061314e+11,2.417566e+11,2.326146e+11,2.630665e+11,3.358830e+11,4.389941e+11,5.649477e+11,5.407657e+11,5.150489e+11,4.896180e+11,4.614871e+11,4.892852e+11,6.014527e+11,7.451626e+11,9.101227e+11,9.268848e+11,1.093169e+12,1.142797e+12,1.179660e+12,1.061389e+12,1.140490e+12,1.335219e+12,1.408782e+12,1.552484e+12,1.638511e+12,1.665624e+12,1.647951e+12,1.621510e+12,1.768408e+12,2.038395e+12,2.398555e+12,2.520702e+12,2.692613e+12,3.074360e+12,2.890564e+12,2.382826e+12,2.441173e+12,2.619700e+12,2.662085e+12,2.739819e+12,3.022828e+12,2.885570e+12,2.647899e+12,6.11,3.70,10.93,59562,United Kingdom,GBR,2016,399.430131,47.824616,173.930280,165.742039,4.553321,4.558600,2.821275,6.083754
1,GB,United Kingdom,GBR,32901036,33746076,2020-12-05,354378,12893,396,4.24,3.35,-36.0,-6.0,-8.0,-41.0,-13.0,8.0,NaN,NaN,NaN,NaN,NaN,NaN,NaN,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,<NA>,<NA>,21.0,GBR,United Kingdom,London,Europe,67508936.0,67059474.0,65224364.0,62760039.0,58850043.0,57210442.0,56326328.0,55650166.0,242900.0,277.9289,1.0034,0.85,7.232805e+10,7.669436e+10,8.060194e+10,8.544377e+10,9.338760e+10,1.005958e+11,1.070907e+11,1.111854e+11,1.047027e+11,1.126769e+11,1.306719e+11,1.481139e+11,1.699650e+11,1.925380e+11,2.061314e+11,2.417566e+11,2.326146e+11,2.630665e+11,3.358830e+11,4.389941e+11,5.649477e+11,5.407657e+11,5.150489e+11,4.896180e+11,4.614871e+11,4.892852e+11,6.014527e+11,7.451626e+11,9.101227e+11,9.268848e+11,1.093169e+12,1.142797e+12,1.179660e+12,1.061389e+12,1.140490e+12,1.335219e+12,1.408782e+12,1.552484e+12,1.638511e+12,1.665624e+12,1.647951e+12,1.621510e+12,1.768408e+12,2.038395e+12,2.398555e+12,2.520702e+12,2.692613e+12,3.074360e+12,2.890564e+12,2.382826e+12,2.441173e+12,2.619700e+12,2.662085e+12,2.739819e+12,3.022828e+12,2.885570e+12,2.647899e+12,6.11,3.70,10.93,59563,United Kingdom,GBR,2017,387.367141,39.128801,174.850612,161.697365,4.409790,4.301261,2.979312,5.863442
2,GB,United Kingdom,GBR,32901036,33746076,2020-12-05,354378,12893,396,4.24,3.35,-36.0,-6.0,-8.0,-41.0,-13.0,8.0,NaN,NaN,NaN,NaN,NaN,NaN,NaN,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,<NA>,<NA>,21.0,GBR,United Kingdom,London,Europe,67508936.0,67059474.0,65224364.0,62760039.0,58850043.0,57210442.0,56326328.0,55650166.0,242900.0,277.9289,1.0034,0.85,7.232805e+10,7.669436e+10,8.060194e+10,8.544377e+10,9.338760e+10,1.005958e+11,1.070907e+11,1.111854e+11,1.047027e+11,1.126769e+11,1.306719e+11,1.481139e+11,1.699650e+11,1.925380e+11,2.061314e+11,2.417566e+11,2.326146e+11,2.630665e+11,3.358830e+11,4.389941e+11,5.649477e+11,5.407657e+11,5.150489e+11,4.896180e+11,4.614871e+11,4.892852e+11,6.014527e+11,7.451626e+11,9.101227e+11,9.268848e+11,1.093169e+12,1.142797e+12,1.179660e+12,1.061389e+12,1.140490e+12,1.335219e+12,1.408782e+12,1.552484e+12,1.638511e+12,1.665624e+12,1.647951e+12,1.621510e+12,1.768408e+12,2.038395e+12,2.398555e+12,2.520702e+12,2.692613e+12,3.074360e+12,2.890564e+12,2.382826e+12,2.441173e+12,2.619700e+12,2.662085e+12,2.739819e+12,3.022828e+12,2.885570e+12,2.647899e+12,6.11,3.70,10.93,59564,United Kingdom,GBR,2018,379.729755,33.280249,173.087118,161.485261,4.363948,4.476409,3.036771,5.715981
3,GB,United Kingdom,GBR,32901036,33746076,2020-12-05,354378,12893,396,4.24,3.35,-36.0,-6.0,-8.0,-41.0,-13.0,8.0,NaN,NaN,NaN,NaN,NaN,NaN,NaN,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,<NA>,<NA>,21.0,GBR,United Kingdom,London,Europe,67508936.0,67059474.0,65224364.0,62760039.0,58850043.0,57210442.0,56326328.0,55650166.0,242900.0,277.9289,1.0034,0.85,7.232805e+10,7.669436e+10,8.060194e+10,8.544377e+10,9.338760e+10,1.005958e+11,1.070907e+11,1.111854e+11,1.047027e+11,1.126769e+11,1.306719e+11,1.481139e+11,1.699650e+11,1.925380e+11,2.061314e+11,2.417566e+11,2.326146e+11,2.630665e+11,3.358830e+11,4.389941e+11,5.649477e+11,5.407657e+11,5.150489e+11,4.896180e+11,4.614871e+11,4.892852e+11,6.014527e+11,7.451626e+11,9.101227e+11,9.268848e+11,1.093169e+12,1.142797e+12,1.179660e+12,1.061389e+12,1.140490e+12,1.335219e+12,1.408782e+12,1.552484e+12,1.638511e+12,1.665624e+12,1.647951e+12,1.621510e+12,1.768408e+12,2.038395e+12,2.398555e+12,2.520702e+12,2.692613e+12,3.074360e+12,2.890564e+12,2.382826e+12,2.441173e+12,2.619700e+12,2.662085e+12,2.739819e+12,3.022828e+12,2.885570e+12,2.647899e+12,6.11,3.70,10.93,59565,United Kingdom,GBR,2019,364.753306,24.512705,168.995529,159.320842,4.448499,4.283190,3.192541,5.462124
4,GB,United Kingdom,GBR,32901036,33746076,2020-12-05,354378,12893,396,4.24,3.35,-36.0,-6.0,-8.0,-41.0,-13.0,8.0,NaN,NaN,NaN,NaN,NaN,NaN,NaN,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,<NA>,<NA>,21.0,GBR,United Kingdom,London,Europe,67508936.0,67059474.0,65224364.0,62760039.0,58850043.0,57210442.0,56326328.0,55650166.0,242900.0,277.9289,1.0034,0.85,7.232805e+10,7.669436e+10,8.060194e+10,8.544377e+10,9.338760e+10,1.005958e+11,1.070907e+11,1.111854e+11,1.047027e+11,1.126769e+11,1.306719e+11,1.481139e+11,1.699650e+11,1.925380e+11,2.061314e+11,2.417566e+11,2.326146e+11,2.630665e+11,3.358830e+11,4.389941e+11,5.649477e+11,5.407657e+11,5.150489e+11,4.896180e+11,4.614871e+11,4.892852e+11,6.014527e+11,7.451626e+11,9.101227e+11,9.268848e+11,1.093169e+12,1.142797e+12,1.179660e+12,1.061389e+12,1.140490e+12,1.335219e+12,1.408782e+12,1.552484e+12,1.638511e+12,1.665624e+12,1.647951e+12,1.621510e+12,1.768408e+12,2.038395e+12,2.398555e+12,2.520702e+12,2.692613e+12,3.074360e+12,2.890564e+12,2.382826e+12,2.441173e+12,2.619700e+12,2.662085e+12,2.739819e+12,3.022828e+12,2.885570e+12,2.647899e+12,6.11,3.70,10.93,59566,United Kingdom,GBR,2020,326.263199,22.809405,143.980921,149.420095,3.899688,3.442599,2.710492,4.865281
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
4249,AU,Australia,AUS,12698625,12801256,2020-07-24,75584,309,7,5.53,4.54,-15.0,1.0,-17.0,-41.0,-16.0,10.0,13595.0,0.0,0.939,NaN,NaN,NaN,NaN,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,<NA>,<NA>,55.0,AUS,Australia,Canberra,Oceania,26177413.0,25670051.0,23820236.0,22019168.0,19017963.0,17048003.0,14706322.0,12595034.0,7692024.0,3.4032,1.0099,0.33,1.859335e+10,1.966626e+10,1.991152e+10,2.152761e+10,2.378766e+10,2.596259e+10,2.728861e+10,3.042110e+10,3.268787e+10,3.665920e+10,4.130474e+10,4.518311e+10,5.200350e+10,6.378219e+10,8.890641e+10,9.722655e+10,1.049742e+11,1.102661e+11,1.184006e+11,1.347938e+11,1.498875e+11,1.768048e+11,1.939545e+11,1.771764e+11,1.935039e+11,1.804710e+11,1.822818e+11,1.893760e+11,2.361358e+11,2.999414e+11,3.114259e+11,3.260686e+11,3.256925e+11,3.123728e+11,3.232169e+11,3.683917e+11,4.018194e+11,4.360980e+11,3.997789e+11,3.891465e+11,4.154462e+11,3.788999e+11,3.946358e+11,4.668532e+11,6.133298e+11,6.937641e+11,7.475726e+11,8.537646e+11,1.055335e+12,9.271683e+11,1.142877e+12,1.390557e+12,1.538194e+12,1.567179e+12,1.459598e+12,1.345383e+12,1.204616e+12,8.49,5.21,4.48,3259,Australia,AUS,2017,414.358312,176.906195,139.460823,76.211806,3.019062,14.861430,3.898995,16.850455
4250,AU,Australia,AUS,12698625,12801256,2020-07-24,75584,309,7,5.53,4.54,-15.0,1.0,-17.0,-41.0,-16.0,10.0,13595.0,0.0,0.939,NaN,NaN,NaN,NaN,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,<NA>,<NA>,55.0,AUS,Australia,Canberra,Oceania,26177413.0,25670051.0,23820236.0,22019168.0,19017963.0,17048003.0,14706322.0,12595034.0,7692024.0,3.4032,1.0099,0.33,1.859335e+10,1.966626e+10,1.991152e+10,2.152761e+10,2.378766e+10,2.596259e+10,2.728861e+10,3.042110e+10,3.268787e+10,3.665920e+10,4.130474e+10,4.518311e+10,5.200350e+10,6.378219e+10,8.890641e+10,9.722655e+10,1.049742e+11,1.102661e+11,1.184006e+11,1.347938e+11,1.498875e+11,1.768048e+11,1.939545e+11,1.771764e+11,1.935039e+11,1.804710e+11,1.822818e+11,1.893760e+11,2.361358e+11,2.999414e+11,3.114259e+11,3.260686e+11,3.256925e+11,3.123728e+11,3.232169e+11,3.683917e+11,4.018194e+11,4.360980e+11,3.997789e+11,3.891465e+11,4.154462e+11,3.788999e+11,3.946358e+11,4.668532e+11,6.133298e+11,6.937641e+11,7.475726e+11,8.537646e+11,1.055335e+12,9.271683e+11,1.142877e+12,1.390557e+12,1.538194e+12,1.567179e+12,1.459598e+12,1.345383e+12,1.204616e+12,8.49,5.21,4.48,3260,Australia,AUS,2018,416.283827,169.370489,143.712379,79.434749,2.941785,16.925628,3.898798,16.665199
4251,AU,Australia,AUS,12698625,12801256,2020-07-24,75584,309,7,5.53,4.54,-15.0,1.0,-17.0,-41.0,-16.0,10.0,13595.0,0.0,0.939,NaN,NaN,NaN,NaN,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,<NA>,<NA>,55.0,AUS,Australia,Canberra,Oceania,26177413.0,25670051.0,23820236.0,22019168.0,19017963.0,17048003.0,14706322.0,12595034.0,7692024.0,3.4032,1.0099,0.33,1.859335e+10,1.966626e+10,1.991152e+10,2.152761e+10,2.378766e+10,2.596259e+10,2.728861e+10,3.042110e+10,3.268787e+10,3.665920e+10,4.130474e+10,4.518311e+10,5.200350e+10,6.378219e+10,8.890641e+10,9.722655e+10,1.049742e+11,1.102661e+11,1.184006e+11,1.347938e+11,1.498875e+11,1.768048e+11,1.939545e+11,1.771764e+11,1.935039e+11,1.804710e+11,1.822818e+11,1.893760e+11,2.361358e+11,2.999414e+11,3.114259e+11,3.260686e+11,3.256925e+11,3.123728e+11,3.232169e+11,3.683917e+11,4.018194e+11,4.360980e+11,3.997789e+11,3.891465e+11,4.154462e+11,3.788999e+11,3.946358e+11,4.668532e+11,6.133298e+11,6.937641e+11,7.475726e+11,8.537646e+11,1.055335e+12,9.271683e+11,1.142877e+12,1.390557e+12,1.538194e+12,1.567179e+12,1.459598e+12,1.345383e+12,1.204616e+12,8.49,5.21,4.48,3261,Australia,AUS,2019,416.356588,164.471156,143.084851,81.693703,3.039547,20.199247,3.868084,16.419679
4252,AU,Australia,AUS,12698625,12801256,2020-07-24,75584,309,7,5.53,4.54,-15.0,1.0,-17.0,-41.0,-16.0,10.0,13595.0,0.0,0.939,NaN,NaN,NaN,NaN,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,<NA>,<NA>,55.0,AUS,Australia,Canberra,Oceania,26177413.0,25670051.0,23820236.0,22019168.0,19017963.0,17048003.0,14706322.0,12595034.0,7692024.0,3.4032,1.0099,0.33,1.859335e+10,1.966626e+10,1.991152e+10,2.152761e+10,2.378766e+10,2.596259e+10,2.728861e+10,3.042110e+10,3.268787e+10,3.665920e+10,4.130474e+10,4.518311e+10,5.200350e+10,6.378219e+10,8.890641e+10,9.722655e+10,1.049742e+11,1.102661e+11,1.184006e+11,1.347938e+11,1.498875e+11,1.768048e+11,1.939545e+11,1.771764e+11,1.935039e+11,1.804710e+11,1.822818e+11,1.893760e+11,2.361358e+11,2.999414e+11,3.114259e+11,3.260686e+11,3.256925e+11,3.123728e+11,3.232169e+11,3.683917e+11,4.018194e+11,4.360980e+11,3.997789e+11,3.891465e+11,4.154462e+11,3.788999e+11,3.946358e+11,4.668532e+11,6.133298e+11,6.937641e+11,7.475726e+11,8.537646e+11,1.055335e+12,9.271683e+11,1.142877e+12,1.390557e+12,1.538194e+12,1.567179e+12,1.459598e+12,1.345383e+12,1.204616e+12,8.49,5.21,4.48,3262,Australia,AUS,2020,399.922128,156.143134,135.476298,84.471564,2.820162,17.272753,3.738217,15.579327
4253,AU,Australia,AUS,12698625,12801256,2020-07-24,75584,309,7,5.53,4.54,-15.0,1.0,-17.0,-41.0,-16.0,10.0,13595.0,0.0,0.939,NaN,NaN,NaN,NaN,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,<NA>,<NA>,55.0,AUS,Australia,Canberra,Oceania,26177413.0,25670051.0,23820236.0,22019168.0,19017963.0,17048003.0,14706322.0,12595034.0,7692024.0,3.4032,1.0099,0.33,1.859335e+10,1.966626e+10,1.991152e+10,2.152761e+10,2.378766e+10,2.596259e+10,2.728861e+10,3.042110e+10,3.268787e+10,3.665920e+10,4.130474e+10,4.518311e+10,5.200350e+10,6.378219e+10,8.890641e+10,9.722655e+10,1.049742e+11,1.102661e+11,1.184006e+11,1.347938e+11,1.498875e+11,1.768048e+11,1.939545e+11,1.771764e+11,1.935039e+11,1.804710e+11,1.822818e+11,1.893760e+11,2.361358e+11,2.999414e+11,3.114259e+11,3.260686e+11,3.256925e+11,3.123728e+11,3.232169e+11,3.683917e+11,4.018194e+11,4.360980e+11,3.997789e+11,3.891465e+11,4.154462e+11,3.788999e+11,3.946358e+11,4.668532e+11,6.133298e+11,6.937641e+11,7.475726e+11,8.537646e+11,1.055335e+12,9.271683e+11,1.142877e+12,1.390557e+12,1.538194e+12,1.567179e+12,1.459598e+12,1.345383e+12,1.204616e+12,8.49,5.21,4.48,3263,Australia,AUS,2021,391.187411,150.958384,139.155751,77.242144,2.820162,17.272753,3.738217,15.091473

In [109]:
# wartośc eksportu
export = pd.read_csv('export_info.csv')
# export
export = export.loc[export['Year'] == 2020]
export = export.groupby(by=['ReporterISO3', 'ReporterName', 'Year']).sum(numeric_only=True).drop_duplicates()
export

                                        TradeValue in 1000 USD
ReporterISO3 ReporterName         Year
ABW          Aruba                2020            1.318618e+05
ALB          Albania              2020            5.029471e+06
ARE          United Arab Emirates 2020            4.734567e+08
ARG          Argentina            2020            1.097676e+08
ARM          Armenia              2020            4.697978e+06
...                                                        ...
VNM          Vietnam              2020            5.628829e+08
ZAF          South Africa         2020            1.700894e+08
ZAR          Congo, Dem. Rep.     2020            2.808553e+07
ZMB          Zambia               2020            1.524224e+07
ZWE          Zimbabwe             2020            8.752753e+06

[139 rows x 1 columns]

In [113]:
gamma = pd.merge(beta, export,
         left_on=['CCA3', 'Year'],
         right_on=['ReporterISO3', 'Year'],
         how='inner')

gamma = gamma.drop(columns=['Unnamed: 0', 'ISO 3166-1 alpha-3', 'Country'])
gamma.to_csv('zad2.3.csv', index=False)
gamma

,location_key,country_name,iso_3166_1_alpha_3,population_male,population_female,date,new_tested,new_confirmed,new_deceased,search_trends_cough,search_trends_fever,mobility_retail_and_recreation,mobility_grocery_and_pharmacy,mobility_parks,mobility_transit_stations,mobility_workplaces,mobility_residential,cumulative_confirmed,cumulative_persons_fully_vaccinated,hdi,new_persons_vaccinated,new_persons_fully_vaccinated,adult_male_mortality_rate,adult_female_mortality_rate,new_deceased_age_0,new_deceased_age_1,new_deceased_age_2,new_deceased_age_3,new_deceased_age_4,new_deceased_age_5,new_deceased_age_6,new_deceased_age_7,new_deceased_age_8,new_deceased_age_9,new_confirmed_age_0,new_confirmed_age_1,new_confirmed_age_2,new_confirmed_age_3,new_confirmed_age_4,new_confirmed_age_5,new_confirmed_age_6,new_confirmed_age_7,new_confirmed_age_8,new_confirmed_age_9,new_recovered,new_intensive_care_patients,Rank,CCA3,Country/Territory,Capital,Continent,2022 Population,2020 Population,2015 Population,2010 Population,2000 Population,1990 Population,1980 Population,1970 Population,Area (km²),Density (per km²),Growth Rate,World Population Percentage,GDP 1960,GDP 1961,GDP 1962,GDP 1963,GDP 1964,GDP 1965,GDP 1966,GDP 1967,GDP 1968,GDP 1969,GDP 1970,GDP 1971,GDP 1972,GDP 1973,GDP 1974,GDP 1975,GDP 1976,GDP 1977,GDP 1978,GDP 1979,GDP 1980,GDP 1981,GDP 1982,GDP 1983,GDP 1984,GDP 1985,GDP 1986,GDP 1987,GDP 1988,GDP 1989,GDP 1990,GDP 1991,GDP 1992,GDP 1993,GDP 1994,GDP 1995,GDP 1996,GDP 1997,GDP 1998,GDP 1999,GDP 2000,GDP 2001,GDP 2002,GDP 2003,GDP 2004,GDP 2005,GDP 2006,GDP 2007,GDP 2008,GDP 2009,GDP 2010,GDP 2011,GDP 2012,GDP 2013,GDP 2014,GDP 2015,GDP 2016,inflation 2017,inflation 2018,inflation 2019,Year,Total,Coal,Oil,Gas,Cement,Flaring,Other,Per Capita,TradeValue in 1000 USD
0,GB,United Kingdom,GBR,32901036,33746076,2020-12-05,354378,12893,396,4.24,3.35,-36.0,-6.0,-8.0,-41.0,-13.0,8.0,NaN,NaN,NaN,NaN,NaN,NaN,NaN,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,<NA>,<NA>,21.0,GBR,United Kingdom,London,Europe,67508936.0,67059474.0,65224364.0,62760039.0,58850043.0,57210442.0,56326328.0,55650166.0,242900.0,277.9289,1.0034,0.85,7.232805e+10,7.669436e+10,8.060194e+10,8.544377e+10,9.338760e+10,1.005958e+11,1.070907e+11,1.111854e+11,1.047027e+11,1.126769e+11,1.306719e+11,1.481139e+11,1.699650e+11,1.925380e+11,2.061314e+11,2.417566e+11,2.326146e+11,2.630665e+11,3.358830e+11,4.389941e+11,5.649477e+11,5.407657e+11,5.150489e+11,4.896180e+11,4.614871e+11,4.892852e+11,6.014527e+11,7.451626e+11,9.101227e+11,9.268848e+11,1.093169e+12,1.142797e+12,1.179660e+12,1.061389e+12,1.140490e+12,1.335219e+12,1.408782e+12,1.552484e+12,1.638511e+12,1.665624e+12,1.647951e+12,1.621510e+12,1.768408e+12,2.038395e+12,2.398555e+12,2.520702e+12,2.692613e+12,3.074360e+12,2.890564e+12,2.382826e+12,2.441173e+12,2.619700e+12,2.662085e+12,2.739819e+12,3.022828e+12,2.885570e+12,2.647899e+12,6.11,3.70,10.93,2020,326.263199,22.809405,143.980921,149.420095,3.899688,3.442599,2.710492,4.865281,7.402990e+08
1,GB,United Kingdom,GBR,32901036,33746076,2020-07-30,206656,946,10,3.37,4.52,-23.0,-7.0,120.0,-41.0,-48.0,13.0,NaN,NaN,NaN,NaN,NaN,NaN,NaN,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,<NA>,<NA>,21.0,GBR,United Kingdom,London,Europe,67508936.0,67059474.0,65224364.0,62760039.0,58850043.0,57210442.0,56326328.0,55650166.0,242900.0,277.9289,1.0034,0.85,7.232805e+10,7.669436e+10,8.060194e+10,8.544377e+10,9.338760e+10,1.005958e+11,1.070907e+11,1.111854e+11,1.047027e+11,1.126769e+11,1.306719e+11,1.481139e+11,1.699650e+11,1.925380e+11,2.061314e+11,2.417566e+11,2.326146e+11,2.630665e+11,3.358830e+11,4.389941e+11,5.649477e+11,5.407657e+11,5.150489e+11,4.896180e+11,4.614871e+11,4.892852e+11,6.014527e+11,7.451626e+11,9.101227e+11,9.268848e+11,1.093169e+12,1.142797e+12,1.179660e+12,1.061389e+12,1.140490e+12,1.335219e+12,1.408782e+12,1.552484e+12,1.638511e+12,1.665624e+12,1.647951e+12,1.621510e+12,1.768408e+12,2.038395e+12,2.398555e+12,2.520702e+12,2.692613e+12,3.074360e+12,2.890564e+12,2.382826e+12,2.441173e+12,2.619700e+12,2.662085e+12,2.739819e+12,3.022828e+12,2.885570e+12,2.647899e+12,6.11,3.70,10.93,2020,326.263199,22.809405,143.980921,149.420095,3.899688,3.442599,2.710492,4.865281,7.402990e+08
2,GB,United Kingdom,GBR,32901036,33746076,2020-09-13,227075,2154,17,8.06,8.08,-21.0,-12.0,94.0,-24.0,-7.0,1.0,NaN,NaN,NaN,NaN,NaN,NaN,NaN,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,<NA>,<NA>,21.0,GBR,United Kingdom,London,Europe,67508936.0,67059474.0,65224364.0,62760039.0,58850043.0,57210442.0,56326328.0,55650166.0,242900.0,277.9289,1.0034,0.85,7.232805e+10,7.669436e+10,8.060194e+10,8.544377e+10,9.338760e+10,1.005958e+11,1.070907e+11,1.111854e+11,1.047027e+11,1.126769e+11,1.306719e+11,1.481139e+11,1.699650e+11,1.925380e+11,2.061314e+11,2.417566e+11,2.326146e+11,2.630665e+11,3.358830e+11,4.389941e+11,5.649477e+11,5.407657e+11,5.150489e+11,4.896180e+11,4.614871e+11,4.892852e+11,6.014527e+11,7.451626e+11,9.101227e+11,9.268848e+11,1.093169e+12,1.142797e+12,1.179660e+12,1.061389e+12,1.140490e+12,1.335219e+12,1.408782e+12,1.552484e+12,1.638511e+12,1.665624e+12,1.647951e+12,1.621510e+12,1.768408e+12,2.038395e+12,2.398555e+12,2.520702e+12,2.692613e+12,3.074360e+12,2.890564e+12,2.382826e+12,2.441173e+12,2.619700e+12,2.662085e+12,2.739819e+12,3.022828e+12,2.885570e+12,2.647899e+12,6.11,3.70,10.93,2020,326.263199,22.809405,143.980921,149.420095,3.899688,3.442599,2.710492,4.865281,7.402990e+08
3,GB,United Kingdom,GBR,32901036,33746076,2020-07-12,101927,366,14,2.96,3.94,-43.0,-15.0,103.0,-27.0,-10.0,3.0,NaN,NaN,NaN,NaN,NaN,NaN,NaN,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,<NA>,<NA>,21.0,GBR,United Kingdom,London,Europe,67508936.0,67059474.0,65224364.0,62760039.0,58850043.0,57210442.0,56326328.0,55650166.0,242900.0,277.9289,1.0034,0.85,7.232805e+10,7.669436e+10,8.060194e+10,8.544377e+10,9.338760e+10,1.005958e+11,1.070907e+11,1.111854e+11,1.047027e+11,1.126769e+11,1.306719e+11,1.481139e+11,1.699650e+11,1.925380e+11,2.061314e+11,2.417566e+11,2.326146e+11,2.630665e+11,3.358830e+11,4.389941e+11,5.649477e+11,5.407657e+11,5.150489e+11,4.896180e+11,4.614871e+11,4.892852e+11,6.014527e+11,7.451626e+11,9.101227e+11,9.268848e+11,1.093169e+12,1.142797e+12,1.179660e+12,1.061389e+12,1.140490e+12,1.335219e+12,1.408782e+12,1.552484e+12,1.638511e+12,1.665624e+12,1.647951e+12,1.621510e+12,1.768408e+12,2.038395e+12,2.398555e+12,2.520702e+12,2.692613e+12,3.074360e+12,2.890564e+12,2.382826e+12,2.441173e+12,2.619700e+12,2.662085e+12,2.739819e+12,3.022828e+12,2.885570e+12,2.647899e+12,6.11,3.70,10.93,2020,326.263199,22.809405,143.980921,149.420095,3.899688,3.442599,2.710492,4.865281,7.402990e+08
4,GB,United Kingdom,GBR,32901036,33746076,2020-11-11,381759,27757,392,5.15,5.15,-49.0,-14.0,-1.0,-51.0,-38.0,16.0,NaN,NaN,NaN,NaN,NaN,NaN,NaN,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,<NA>,<NA>,21.0,GBR,United Kingdom,London,Europe,67508936.0,67059474.0,65224364.0,62760039.0,58850043.0,57210442.0,56326328.0,55650166.0,242900.0,277.9289,1.0034,0.85,7.232805e+10,7.669436e+10,8.060194e+10,8.544377e+10,9.338760e+10,1.005958e+11,1.070907e+11,1.111854e+11,1.047027e+11,1.126769e+11,1.306719e+11,1.481139e+11,1.699650e+11,1.925380e+11,2.061314e+11,2.417566e+11,2.326146e+11,2.630665e+11,3.358830e+11,4.389941e+11,5.649477e+11,5.407657e+11,5.150489e+11,4.896180e+11,4.614871e+11,4.892852e+11,6.014527e+11,7.451626e+11,9.101227e+11,9.268848e+11,1.093169e+12,1.142797e+12,1.179660e+12,1.061389e+12,1.140490e+12,1.335219e+12,1.408782e+12,1.552484e+12,1.638511e+12,1.665624e+12,1.647951e+12,1.621510e+12,1.768408e+12,2.038395e+12,2.398555e+12,2.520702e+12,2.692613e+12,3.074360e+12,2.890564e+12,2.382826e+12,2.441173e+12,2.619700e+12,2.662085e+12,2.739819e+12,3.022828e+12,2.885570e+12,2.647899e+12,6.11,3.70,10.93,2020,326.263199,22.809405,143.980921,149.420095,3.899688,3.442599,2.710492,4.865281,7.402990e+08
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
704,AU,Australia,AUS,12698625,12801256,2020-12-20,46358,44,0,5.51,4.40,-2.0,6.0,-8.0,-30.0,-3.0,1.0,28172.0,0.0,0.939,NaN,NaN,NaN,NaN,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,<NA>,<NA>,55.0,AUS,Australia,Canberra,Oceania,26177413.0,25670051.0,23820236.0,22019168.0,19017963.0,17048003.0,14706322.0,12595034.0,7692024.0,3.4032,1.0099,0.33,1.859335e+10,1.966626e+10,1.991152e+10,2.152761e+10,2.378766e+10,2.596259e+10,2.728861e+10,3.042110e+10,3.268787e+10,3.665920e+10,4.130474e+10,4.518311e+10,5.200350e+10,6.378219e+10,8.890641e+10,9.722655e+10,1.049742e+11,1.102661e+11,1.184006e+11,1.347938e+11,1.498875e+11,1.768048e+11,1.939545e+11,1.771764e+11,1.935039e+11,1.804710e+11,1.822818e+11,1.893760e+11,2.361358e+11,2.999414e+11,3.114259e+11,3.260686e+11,3.256925e+11,3.123728e+11,3.232169e+11,3.683917e+11,4.018194e+11,4.360980e+11,3.997789e+11,3.891465e+11,4.154462e+11,3.788999e+11,3.946358e+11,4.668532e+11,6.133298e+11,6.937641e+11,7.475726e+11,8.537646e+11,1.055335e+12,9.271683e+11,1.142877e+12,1.390557e+12,1.538194e+12,1.567179e+12,1.459598e+12,1.345383e+12,1.204616e+12,8.49,5.21,4.48,2020,399.922128,156.143134,135.476298,84.471564,2.820162,17.272753,3.738217,15.579327,4.900919e+08
705,AU,Australia,AUS,12698625,12801256,2020-11-09,29026,10,0,5.91,5.61,-12.0,0.0,-15.0,-41.0,-9.0,5.0,27668.0,0.0,0.939,NaN,NaN,NaN,NaN,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,<NA>,<NA>,55.0,AUS,Australia,Canberra,Oceania,26177413.0,25670051.0,23820236.0,22019168.0,19017963.0,17048003.0,14706322.0,12595034.0,7692024.0,3.4032,1.0099,0.33,1.859335e+10,1.966626e+10,1.991152e+10,2.152761e+10,2.378766e+10,2.596259e+10,2.728861e+10,3.042110e+10,3.268787e+10,3.665920e+10,4.130474e+10,4.518311e+10,5.200350e+10,6.378219e+10,8.890641e+10,9.722655e+10,1.049742e+11,1.102661e+11,1.184006e+11,1.347938e+11,1.498875e+11,1.768048e+11,1.939545e+11,1.771764e+11,1.935039e+11,1.804710e+11,1.822818e+11,1.893760e+11,2.361358e+11,2.999414e+11,3.114259e+11,3.260686e+11,3.256925e+11,3.123728e+11,3.232169e+11,3.683917e+11,4.018194e+11,4.360980e+11,3.997789e+11,3.891465e+11,4.154462e+11,3.788999e+11,3.946358e+11,4.668532e+11,6.133298e+11,6.937641e+11,7.475726e+11,8.537646e+11,1.055335e+12,9.271683e+11,1.142877e+12,1.390557e+12,1.538194e+12,1.567179e+12,1.459598e+12,1.345383e+12,1.204616e+12,8.49,5.21,4.48,2020,399.922128,156.143134,135.476298,84.471564,2.820162,17.272753,3.738217,15.579327,4.900919e+08
706,AU,Australia,AUS,12698625,12801256,2020-08-06,89981,483,8,5.85,5.36,-23.0,-8.0,-10.0,-46.0,-22.0,12.0,19863.0,0.0,0.939,NaN,NaN,NaN,NaN,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,<NA>,<NA>,55.0,AUS,Australia,Canberra,Oceania,26177413.0,25670051.0,23820236.0,22019168.0,19017963.0,17048003.0,14706322.0,12595034.0,7692024.0,3.4032,1.0099,0.33,1.859335e+10,1.966626e+10,1.991152e+10,2.152761e+10,2.378766e+10,2.596259e+10,2.728861e+10,3.042110e+10,3.268787e+10,3.665920e+10,4.130474e+10,4.518311e+10,5.200350e+10,6.378219e+10,8.890641e+10,9.722655e+10,1.049742e+11,1.102661e+11,1.184006e+11,1.347938e+11,1.498875e+11,1.768048e+11,1.939545e+11,1.771764e+11,1.935039e+11,1.804710e+11,1.822818e+11,1.893760e+11,2.361358e+11,2.999414e+11,3.114259e+11,3.260686e+11,3.256925e+11,3.123728e+11,3.232169e+11,3.683917e+11,4.018194e+11,4.360980e+11,3.997789e+11,3.891465e+11,4.154462e+11,3.788999e+11,3.946358e+11,4.668532e+11,6.133298e+11,6.937641e+11,7.475726e+11,8.537646e+11,1.055335e+12,9.271683e+11,1.142877e+12,1.390557e+12,1.538194e+12,1.567179e+12,1.459598e+12,1.345383e+12,1.204616e+12,8.49,5.21,4.48,2020,399.922128,156.143134,135.476298,84.471564,2.820162,17.272753,3.738217,15.579327,4.900919e+08
707,AU,Australia,AUS,12698625,12801256,2020-07-25,64084,372,5,5.33,4.53,-15.0,-2.0,-15.0,-39.0,-11.0,8.0,13950.0,0.0,0.939,NaN,NaN,NaN,NaN,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,<NA>,<NA>,55.0,AUS,Australia,Canberra,Oceania,26177413.0,25670051.0,23820236.0,22019168.0,19017963.0,17048003.0,14706322.0,12595034.0,7692024.0,3.4032,1.0099,0.33,1.859335e+10,1.966626e+10,1.991152e+10,2.152761e+10,2.378766e+10,2.596259e+10,2.728861e+10,3.042110e+10,3.268787e+10,3.665920e+10,4.130474e+10,4.518311e+10,5.200350e+10,6.378219e+10,8.890641e+10,9.722655e+10,1.049742e+11,1.102661e+11,1.184006e+11,1.347938e+11,1.498875e+11,1.768048e+11,1.939545e+11,1.771764e+11,1.935039e+11,1.804710e+11,1.822818e+11,1.893760e+11,2.361358e+11,2.999414e+11,3.114259e+11,3.260686e+11,3.256925e+11,3.123728e+11,3.232169e+11,3.683917e+11,4.018194e+11,4.360980e+11,3.997789e+11,3.891465e+11,4.154462e+11,3.788999e+11,3.946358e+11,4.668532e+11,6.133298e+11,6.937641e+11,7.475726e+11,8.537646e+11,1.055335e+12,9.271683e+11,1.142877e+12,1.390557e+12,1.538194e+12,1.567179e+12,1.459598e+12,1.345383e+12,1.204616e+12,8.49,5.21,4.48,2020,399.922128,156.143134,135.476298,84.471564,2.820162,17.272753,3.738217,15.579327,4.900919e+08
708,AU,Australia,AUS,12698625,12801256,2020-07-24,75584,309,7,5.53,4.54,-15.0,1.0,-17.0,-41.0,-16.0,10.0,13595.0,0.0,0.939,NaN,NaN,NaN,NaN,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,<NA>,<NA>,55.0,AUS,Australia,Canberra,Oceania,26177413.0,25670051.0,23820236.0,22019168.0,19017963.0,17048003.0,14706322.0,12595034.0,7692024.0,3.4032,1.0099,0.33,1.859335e+10,1.966626e+10,1.991152e+10,2.152761e+10,2.378766e+10,2.596259e+10,2.728861e+10,3.042110e+10,3.268787e+10,3.665920e+10,4.130474e+10,4.518311e+10,5.200350e+10,6.378219e+10,8.890641e+10,9.722655e+10,1.049742e+11,1.102661e+11,1.184006e+11,1.347938e+11,1.498875e+11,1.768048e+11,1.939545e+11,1.771764e+11,1.935039e+11,1.804710e+11,1.822818e+11,1.893760e+11,2.361358e+11,2.999414e+11,3.114259e+11,3.260686e+11,3.256925e+11,3.123728e+11,3.232169e+11,3.683917e+11,4.018194e+11,4.360980e+11,3.997789e+11,3.891465e+11,4.154462e+11,3.788999e+11,3.946358e+11,4.668532e+11,6.133298e+11,6.937641e+11,7.475726e+11,8.537646e+11,1.055335e+12,9.271683e+11,1.142877e+12,1.390557e+12,1.538194e+12,1.567179e+12,1.459598e+12,1.345383e+12,1.204616e+12,8.49,5.21,4.48,2020,399.922128,156.143134,135.476298,84.471564,2.820162,17.272753,3.738217,15.579327,4.900919e+08